### PR TITLE
Make sure ctype(3) function arguments are valid.

### LINKED ISSUE #4620: unsafe use of ctype(3) interfaces
The [ctype(3)](https://man.netbsd.org/ctype.3) functions only accept, per ANSI and POSIX, values representable as `unsigned char` and `EOF` (which is usually `-1`).

NetBSD is especially picky about enforcing this.

On NetBSD 10.99.14, neomutt 20250404 just coredumps on startup, with the following backtrace:
```
(gdb) bt
#0  0x0000000000623bfa in parse_extract_token (dest=dest@entry=0x74a13e5574e0, tok=tok@entry=0x74a13e557480, flags=flags@entry=76) at parse/extract.c:65
#1  0x000000000057b692 in parse_alias (buf=0x74a13e5574e0, s=0x74a13e557480, data=<optimized out>, err=0x74a13e557580) at alias/commands.c:158
#2  0x00000000006245c6 in parse_rc_buffer (err=0x74a13e557580, token=0x74a13e5574e0, line=0x74a13e557480) at parse/rc.c:81
#3  parse_rc_buffer (line=0x74a13e557480, token=0x74a13e5574e0, err=err@entry=0x74a13e557580) at parse/rc.c:47
#4  0x00000000005291fb in source_rc (rcfile_path=<optimized out>, err=err@entry=0x74a13e557580) at commands.c:295
#5  0x000000000052961c in parse_source (buf=0x74a13e5574a0, s=0x74a13e5574c0, data=<optimized out>, err=0x74a13e557580) at commands.c:1104
#6  0x00000000006245c6 in parse_rc_buffer (err=0x74a13e557580, token=0x74a13e5574a0, line=0x74a13e5574c0) at parse/rc.c:81
#7  parse_rc_buffer (line=0x74a13e5574c0, token=0x74a13e5574a0, err=err@entry=0x74a13e557580) at parse/rc.c:47
#8  0x00000000005291fb in source_rc (rcfile_path=<optimized out>, err=err@entry=0x74a13e557580) at commands.c:295
#9  0x000000000052961c in parse_source (buf=0x74a13e557520, s=0x74a13e557500, data=<optimized out>, err=0x74a13e557580) at commands.c:1104
#10 0x00000000006245c6 in parse_rc_buffer (err=0x74a13e557580, token=0x74a13e557520, line=0x74a13e557500) at parse/rc.c:81
#11 parse_rc_buffer (line=0x74a13e557500, token=0x74a13e557520, err=err@entry=0x74a13e557580) at parse/rc.c:47
#12 0x00000000005291fb in source_rc (rcfile_path=<optimized out>, err=0x74a13e557580) at commands.c:295
#13 0x00000000006519bd in mutt_init (commands=0x74a13e194020, user_files=0x74a13e194008, skip_sys_rc=false, dfile=0x74a13e194060, dlevel=0x74a13e194048, cs=0x74a13e18d000) at main.c:620
#14 main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at main.c:1215
(gdb) fr 0
#0  0x0000000000623bfa in parse_extract_token (dest=dest@entry=0x74a13e5574e0, tok=tok@entry=0x74a13e557480, flags=flags@entry=76) at parse/extract.c:65
65      in parse/extract.c
```
and the following patch fixes this:
```
--- parse/extract.c.orig        2025-05-05 09:51:07.682959138 +0000
+++ parse/extract.c
@@ -62,7 +62,7 @@ int parse_extract_token(struct Buffer *d
   {
     if (qc == '\0')
     {
-      if (isspace(ch) && !(flags & TOKEN_SPACE))
+      if (isspace((unsigned char)ch) && !(flags & TOKEN_SPACE))
         break;
       if ((ch == '#') && !(flags & TOKEN_COMMENT))
         break;
```
but there are many more warnings about ctype functions in the build log:
```
In file included from /usr/include/ctype.h:100,
                 from muttlib.c:34:
muttlib.c: In function 'mutt_safe_path':
muttlib.c:686:32: warning: array subscript has type 'char' [-Wchar-subscripts]
  686 |     if ((*p == '/') || isspace(*p) || !IsPrint((unsigned char) *p))
      |                                ^
muttlib.c: In function 'mutt_encode_path':
muttlib.c:867:27: warning: array subscript has type 'char' [-Wchar-subscripts]
  867 |     if (!isalnum(buf->data[i]) && !strchr("/.-_", buf->data[i]))
      |                           ^
In file included from /usr/include/ctype.h:100,
                 from handler.c:37:
handler.c: In function 'decode_quoted':
handler.c:340:43: warning: array subscript has type 'char' [-Wchar-subscripts]
  340 |       while ((linelen > 0) && isspace(line[linelen - 1]))
      |                                           ^
In file included from /usr/include/ctype.h:100,
                 from mutt_config.c:36:
mutt_config.c: In function 'parse_tags_transformed':
mutt_config.c:249:19: warning: array subscript has type 'char' [-Wchar-subscripts]
  249 |   if (!isalnum(str[1]))
      |                   ^
In file included from /usr/include/ctype.h:100,
                 from pager/display.c:32:
pager/display.c: In function 'check_sig':
pager/display.c:78:20: warning: array subscript has type 'char' [-Wchar-subscripts]
   78 |       if (!isspace(*s))
      |                    ^
In file included from /usr/include/ctype.h:100,
                 from question/question.c:31:
question/question.c: In function 'mw_multi_choice':
question/question.c:86:22: warning: array subscript has type 'char' [-Wchar-subscripts]
   86 |       if (isalnum(cur[1]) && (cur[2] == ')'))
      |                      ^
In file included from /usr/include/ctype.h:100,
                 from send/sendlib.c:33:
send/sendlib.c: In function 'mutt_lookup_mime_type':
send/sendlib.c:154:40: warning: array subscript has type 'char' [-Wchar-subscripts]
  154 |             for (q = p; *q && !isspace(*q); q++)
      |                                        ^
In file included from /usr/include/ctype.h:100,
                 from key/lib.c:30:
key/lib.c: In function 'parse_fkey':
key/lib.c:170:34: warning: array subscript has type 'char' [-Wchar-subscripts]
  170 |   if ((s[0] != '<') || (tolower(s[1]) != 'f'))
      |                                  ^
key/lib.c: In function 'parse_keycode':
key/lib.c:197:18: warning: array subscript has type 'char' [-Wchar-subscripts]
  197 |   while (isspace(*end_char))
      |                  ^
In file included from /usr/include/ctype.h:100,
                 from nntp/nntp.c:35:
nntp/nntp.c: In function 'nntp_auth':
nntp/nntp.c:489:20: warning: array subscript has type 'char' [-Wchar-subscripts]
  489 |       *p = toupper(*p);
      |                    ^
In file included from /usr/include/ctype.h:100,
                 from color/parse_ansi.c:30:
color/parse_ansi.c: In function 'ansi_color_seq_length':
color/parse_ansi.c:88:42: warning: array subscript has type 'char' [-Wchar-subscripts]
   88 |   while ((str[i] != '\0') && (isdigit(str[i]) || (str[i] == ';')))
      |                                          ^
color/parse_ansi.c: In function 'ansi_color_parse_single':
color/parse_ansi.c:122:41: warning: array subscript has type 'char' [-Wchar-subscripts]
  122 |     if ((buf[pos] == '0') && isdigit(buf[pos + 1]))
      |                                         ^
color/parse_ansi.c:136:46: warning: array subscript has type 'char' [-Wchar-subscripts]
  136 |     else if ((buf[pos] == '2') && isdigit(buf[pos + 1]) && ansi_is_end_char(buf[pos + 2]))
      |                                              ^
color/parse_ansi.c:179:67: warning: array subscript has type 'char' [-Wchar-subscripts]
  179 |         if (mutt_str_startswith(buf + pos, "38;5;") && isdigit(buf[pos + 5]))
      |                                                                   ^
color/parse_ansi.c:195:72: warning: array subscript has type 'char' [-Wchar-subscripts]
  195 |         else if (mutt_str_startswith(buf + pos, "38;2;") && isdigit(buf[pos + 5]))
      |                                                                        ^
color/parse_ansi.c:267:67: warning: array subscript has type 'char' [-Wchar-subscripts]
  267 |         if (mutt_str_startswith(buf + pos, "48;5;") && isdigit(buf[pos + 5]))
      |                                                                   ^
color/parse_ansi.c:283:72: warning: array subscript has type 'char' [-Wchar-subscripts]
  283 |         else if (mutt_str_startswith(buf + pos, "48;2;") && isdigit(buf[pos + 5]))
      |                                                                        ^
In file included from /usr/include/ctype.h:100,
                 from ./mutt/mbyte.h:27,
                 from ./mutt/lib.h:88,
                 from color/parse_color.c:31:
color/parse_color.c: In function 'parse_color_pair':
./parse/extract.h:36:15: warning: array subscript has type 'char' [-Wchar-subscripts]
   36 |     (!isspace(*(buf)->dptr) || ((flags) & TOKEN_SPACE)) && \
      |               ^
color/parse_color.c:286:10: note: in expansion of macro 'MoreArgsF'
  286 |     if (!MoreArgsF(s, TOKEN_COMMENT))
      |          ^~~~~~~~~
./parse/extract.h:36:15: warning: array subscript has type 'char' [-Wchar-subscripts]
   36 |     (!isspace(*(buf)->dptr) || ((flags) & TOKEN_SPACE)) && \
      |               ^
color/parse_color.c:311:8: note: in expansion of macro 'MoreArgsF'
  311 |   if (!MoreArgsF(s, TOKEN_COMMENT))
      |        ^~~~~~~~~
In file included from /usr/include/ctype.h:100,
                 from notmuch/tag.c:31:
notmuch/tag.c: In function 'nm_tag_str_to_tags':
notmuch/tag.c:62:25: warning: array subscript has type 'char' [-Wchar-subscripts]
   62 |     if (!tag && isspace(*p))
      |                         ^
In file included from /usr/include/ctype.h:100,
                 from maildir/config.c:31:
maildir/config.c: In function 'maildir_field_delimiter_validator':
maildir/config.c:56:15: warning: array subscript has type 'char' [-Wchar-subscripts]
   56 |   if (isalnum(*delim) || strchr("-.\\/", *delim))
      |               ^
In file included from /usr/include/ctype.h:100,
                 from ncrypt/gpgme_functions.c:31:
ncrypt/gpgme_functions.c: In function 'parse_dn_part':
ncrypt/gpgme_functions.c:198:28: warning: array subscript has type 'char' [-Wchar-subscripts]
  198 |     for (s = str; isxdigit(*s); s++)
      |                            ^
ncrypt/gpgme_functions.c:222:28: warning: array subscript has type 'char' [-Wchar-subscripts]
  222 |         else if (isxdigit(s[0]) && isxdigit(s[1]))
      |                            ^
ncrypt/gpgme_functions.c:222:46: warning: array subscript has type 'char' [-Wchar-subscripts]
  222 |         else if (isxdigit(s[0]) && isxdigit(s[1]))
      |                                              ^
ncrypt/gpgme_functions.c:254:22: warning: array subscript has type 'char' [-Wchar-subscripts]
  254 |         if (isxdigit(*s))
      |                      ^
ncrypt/gpgme_functions.c: In function 'parse_and_print_user_id':
ncrypt/gpgme_functions.c:358:27: warning: array subscript has type 'char' [-Wchar-subscripts]
  358 |   else if (!isalnum(userid[0]))
      |                           ^
In file included from /usr/include/ctype.h:100,
                 from imap/command.c:38:
imap/command.c: In function 'cmd_parse_capability':
imap/command.c:561:53: warning: array subscript has type 'char' [-Wchar-subscripts]
  561 |       if (len != 0 && ((s[len] == '\0') || isspace(s[len])))
      |                                                     ^
In file included from /usr/include/ctype.h:100,
                 from imap/imap.c:43:
imap/imap.c: In function 'get_flags':
In file included from /usr/include/ctype.h:100,
                 from imap/message.c:37:
imap/message.c: In function 'msg_parse_flags':
imap/imap.c:156:42: warning: array subscript has type 'char' [-Wchar-subscripts]
  156 |     while (*s && (*s != ')') && !isspace(*s))
      |                                          ^
imap/message.c:259:29: warning: array subscript has type 'char' [-Wchar-subscripts]
  259 |       while (*s && !isspace(*s) && (*s != ')'))
      |                             ^
In file included from /usr/include/ctype.h:100,
                 from imap/util.c:36:
imap/util.c: In function 'imap_next_word':
imap/util.c:839:28: warning: array subscript has type 'char' [-Wchar-subscripts]
  839 |     if (!quoted && isspace(*s))
      |                            ^
mkdir -p /scratch/mail/neomutt/work/neomutt-20250404/hcache
( echo '#include "config.h"'; \
echo '#include "address/address.h"'; \
echo '#include "email/body.h"'; \
echo '#include "email/email.h"'; \
echo '#include "email/envelope.h"'; \
echo '#include "email/parameter.h"'; \
echo '#include "mutt/buffer.h"'; \
sh ./hcache/hcachever.sh hcache/hcversion.h
In file included from /usr/include/ctype.h:100,
                 from expando/node_conddate.c:31:
expando/node_conddate.c: In function 'node_conddate_parse':
expando/node_conddate.c:233:15: warning: array subscript has type 'char' [-Wchar-subscripts]
  233 |   if (isdigit(*str))
      |               ^
In file included from /usr/include/ctype.h:100,
                 from expando/node_expando.c:31:
expando/node_expando.c: In function 'parse_format':
expando/node_expando.c:171:15: warning: array subscript has type 'char' [-Wchar-subscripts]
  171 |   if (isdigit(*str))
      |               ^
expando/node_expando.c:195:17: warning: array subscript has type 'char' [-Wchar-subscripts]
  195 |     if (isdigit(*str))
      |                 ^
In file included from /usr/include/ctype.h:100,
                 from email/parse.c:36:
email/parse.c: In function 'mutt_parse_content_type':
email/parse.c:476:27: warning: array subscript has type 'char' [-Wchar-subscripts]
  476 |     while (*pc && isspace(*pc))
      |                           ^
email/parse.c:498:40: warning: array subscript has type 'char' [-Wchar-subscripts]
  498 |     for (pc = subtype; *pc && !isspace(*pc) && (*pc != ';'); pc++)
      |                                        ^
email/parse.c: In function 'parse_multipart':
email/parse.c:1623:45: warning: array subscript has type 'char' [-Wchar-subscripts]
 1623 |         for (size_t i = len - 1; isspace(buf[i]) && (i >= (blen + 2)); i--)
      |                                             ^
In file included from /usr/include/ctype.h:100,
                 from email/rfc2047.c:34:
email/rfc2047.c: In function 'parse_encoded_word':
email/rfc2047.c:165:22: warning: array subscript has type 'char' [-Wchar-subscripts]
  165 |   *enc = (tolower(str[mutt_regmatch_start(mencoding)]) == 'q') ? ENC_QUOTED_PRINTABLE : ENC_BASE64;
      |                      ^
In file included from /usr/include/ctype.h:100,
                 from mutt/date.c:37:
mutt/date.c: In function 'mutt_date_parse_rfc5322_strict':
mutt/date.c:657:21: warning: array subscript has type 'char' [-Wchar-subscripts]
  657 |       if (!isalpha(s[i]) && (s[i] != ' '))
      |                     ^
mutt/date.c:682:23: warning: array subscript has type 'char' [-Wchar-subscripts]
  682 |         if (!isalpha(s[i]))
      |                       ^
In file included from /usr/include/ctype.h:100,
                 from mutt/file.c:39:
mutt/file.c: In function 'mutt_file_read_keyword':
mutt/file.c:1314:37: warning: array subscript has type 'char' [-Wchar-subscripts]
 1314 |   while ((*buf != '\0') && !isspace(*buf))
      |                                     ^
In file included from /usr/include/ctype.h:100,
                 from mutt/mbyte.c:31:
mutt/mbyte.c: In function 'mutt_mb_get_initials':
mutt/mbyte.c:95:32: warning: array subscript has type 'char' [-Wchar-subscripts]
   95 |     if ((clen == 1) && ispunct(*name))
      |                                ^
mutt/mbyte.c:115:35: warning: array subscript has type 'char' [-Wchar-subscripts]
  115 |       if ((clen == 1) && (isspace(*name) || (*name == '-')))
      |                                   ^
mutt/mbyte.c:120:30: warning: array subscript has type 'char' [-Wchar-subscripts]
  120 |     while (*name && (isspace(*name) || (*name == '-')))
      |                              ^
mkdir -p po
msgfmt -c -o po/bg.mo po/bg.po
msgfmt -c -o po/ca.mo po/ca.po
msgfmt -c -o po/cs.mo po/cs.po
msgfmt -c -o po/da.mo po/da.po
msgfmt -c -o po/de.mo po/de.po
msgfmt -c -o po/el.mo po/el.po
msgfmt -c -o po/en_GB.mo po/en_GB.po
In file included from /usr/include/ctype.h:100,
                 from mutt/string.c:34:
mutt/string.c: In function 'startswith':
mutt/string.c:215:32: warning: array subscript has type 'char' [-Wchar-subscripts]
  215 |     if (!match_case && tolower(*str) == tolower(*prefix))
      |                                ^
msgfmt -c -o po/eo.mo po/eo.po
mutt/string.c:215:49: warning: array subscript has type 'char' [-Wchar-subscripts]
  215 |     if (!match_case && tolower(*str) == tolower(*prefix))
      |                                                 ^
mutt/string.c: In function 'mutt_str_remove_trailing_ws':
mutt/string.c:571:63: warning: array subscript has type 'char' [-Wchar-subscripts]
  571 |   for (char *p = s + mutt_str_len(s) - 1; (p >= s) && isspace(*p); p--)
      |                                                               ^
mutt/string.c: In function 'mutt_str_inbox_cmp':
mutt/string.c:890:69: warning: array subscript has type 'char' [-Wchar-subscripts]
  890 | #define IS_INBOX(s) (mutt_istrn_equal(s, "inbox", 5) && !isalnum((s)[5]))
      |                                                                     ^
mutt/string.c:891:26: note: in expansion of macro 'IS_INBOX'
  891 | #define CMP_INBOX(a, b) (IS_INBOX(b) - IS_INBOX(a))
      |                          ^~~~~~~~
mutt/string.c:896:12: note: in expansion of macro 'CMP_INBOX'
  896 |     return CMP_INBOX(a + 1, b + 1);
      |            ^~~~~~~~~
mutt/string.c:890:69: warning: array subscript has type 'char' [-Wchar-subscripts]
  890 | #define IS_INBOX(s) (mutt_istrn_equal(s, "inbox", 5) && !isalnum((s)[5]))
      |                                                                     ^
mutt/string.c:891:40: note: in expansion of macro 'IS_INBOX'
  891 | #define CMP_INBOX(a, b) (IS_INBOX(b) - IS_INBOX(a))
      |                                        ^~~~~~~~
mutt/string.c:896:12: note: in expansion of macro 'CMP_INBOX'
  896 |     return CMP_INBOX(a + 1, b + 1);
      |            ^~~~~~~~~
mutt/string.c:890:69: warning: array subscript has type 'char' [-Wchar-subscripts]
  890 | #define IS_INBOX(s) (mutt_istrn_equal(s, "inbox", 5) && !isalnum((s)[5]))
      |                                                                     ^
mutt/string.c:891:26: note: in expansion of macro 'IS_INBOX'
  891 | #define CMP_INBOX(a, b) (IS_INBOX(b) - IS_INBOX(a))
      |                          ^~~~~~~~
mutt/string.c:920:10: note: in expansion of macro 'CMP_INBOX'
  920 |   return CMP_INBOX(a + 1 + min, b + 1 + min);
      |          ^~~~~~~~~
mutt/string.c:890:69: warning: array subscript has type 'char' [-Wchar-subscripts]
  890 | #define IS_INBOX(s) (mutt_istrn_equal(s, "inbox", 5) && !isalnum((s)[5]))
      |                                                                     ^
mutt/string.c:891:40: note: in expansion of macro 'IS_INBOX'
  891 | #define CMP_INBOX(a, b) (IS_INBOX(b) - IS_INBOX(a))
      |                                        ^~~~~~~~
mutt/string.c:920:10: note: in expansion of macro 'CMP_INBOX'
  920 |   return CMP_INBOX(a + 1 + min, b + 1 + min);
      |          ^~~~~~~~~
```

### PR DESCRIPTION
**Pull request by 0-wiz-0**
Fixes #4620.

### CODE REVIEW

**Comment by gahr** [comment]
For the same reason we're discussing in that other issue #4656, I think you should name the new header with a name that doesn't clash with libc. That's why we have `string2.h` instead of `string.h`.

File: complete/helpers.c [hunk 1]
```diff
@@ -45,6 +44,7 @@
 #include "menu/lib.h"
 #include "compapi.h"
 #include "data.h"
+#include "mutt/ctype2.h"
```
Comment (gahr) [inline complete/helpers.c:47]: You should include this from `mutt/lib.h`. Most files would already include `mutt/lib.h` so you don't have to tweak the includes of everything

**Comment by gahr** [comment]
Why do we still have casts to unsigned char around?

**Comment by 0-wiz-0** [comment]
Because I don't know which parts of the source code are synced with mutt and wanted to keep the diffs small.

**Comment by gahr** [comment]
> Because I don't know which parts of the source code are synced with mutt and wanted to keep the diffs small.

Ah, don't worry about that.. especially in your new code

**Comment by gahr** [comment]
I think code that calls your new functions are "new code" :) really, let's do without the casts

**Review by gahr — APPROVED** [review]
LGTM, thanks!

File: mutt/ctype2.h [hunk 2]
```diff
@@ -0,0 +1,35 @@
+/**
+ * @file
+ * ctype(3) wrapper functions
```
Comment (roccoblues) [inline mutt/ctype2.h:3]: Mind explaining the reason from wrapping a bit here?

File: key/init.c [hunk 3]
```diff
@@ -53,6 +53,7 @@ extern const struct MenuOpSeq PostponedDefaultBindings[];
 extern const struct MenuOpSeq QueryDefaultBindings[];
 extern const struct MenuOpSeq SmimeDefaultBindings[];
 
+#ifdef HAVE_USE_EXTENDED_NAMES
```
Comment (roccoblues) [inline key/init.c:56]: This seems unrelated?

File: mutt/ctype2.h (hunk 2 above)
Comment (0-wiz-0) [reply mutt/ctype2.h:3]: Done.

File: key/init.c (hunk 3 above)
Comment (gahr) [reply key/init.c:56]: Oh  I totally missed this

Comment (0-wiz-0) [reply key/init.c]: I've moved that diff to #4657.
