### PR TITLE
expand tabs to spaces in compose preview (fixes #4534)

### LINKED ISSUE #4534: compose_show_preview renders <TAB> character as questionmark
## NeoMutt Version

```
neomutt -v              
NeoMutt 20250109-dirty
Copyright (C) 2015-2025 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 6.13.0-rc6-1-mainline (x86_64)
ncurses: ncurses 6.5.20240427 (compiled with 6.5.20240427)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.24.1
GnuTLS: 3.8.8
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb
compression: lz4, zlib, zstd

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm --ubsan --lz4 --zlib --zstd

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/neomutt/src=/usr/src/debug/neomutt -flto=auto -std=c11 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -I/usr/include -I/usr/include -I/usr/include -DNCURSES_WIDECHAR -I/usr/include -I/usr/include/p11-kit-1 -I/usr/include -I/usr/include -fsanitize=undefined -fno-omit-frame-pointer -fno-common -g -O0

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme 
  -gsasl +gss +hcache -homespool +idn +inotify -locales_hack +lua +nls +notmuch 
  -openssl +pgp +regex +sasl +smime +sqlite +truecolor 

Devel options:
  ubsan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Expected Behaviour

I was sending a mail which contained a patch with code that was indented by tab characters. I was expecting the send-preview to render these characters properly like the full windowed preview does.

Screenshots2025-01-10_10:04:05

## Actual Behaviour

All <TAB> characters were rendered as "?"

Screenshots2025-01-10_10:04:00

## Steps to Reproduce

have `set compose_show_preview = yes` in your config
preview a mail that contains tabs

## How often does this happen?

Always 

## When did it start to happen?

I don't know when it started to happen, if it is of interest I can compare the behavior with the previous version of neomutt.

## Extra Info

* Operating System and its version: Arch Linux (rolling)
* Were you using multiple copies of NeoMutt at once? no
* Were you using 'screen' or 'tmux'? no
* Is your email local (maildir) or remote (IMAP)? local

### PR DESCRIPTION
**Pull request by roccoblues**
As reported in (#4534), the message preview in the compose window incorrectly rendered tabs (`\t`) as `?`.

The reason was that `mutt_paddstr()` replaces everything that is not `IsWPrint()` with `?`. To fix this we expand the tabs in each line before we measure the width and print it.

### CODE REVIEW

File: test/string/mutt_str_expand_tabs.c [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+    char *str = mutt_str_dup("apple");
+    char *result = mutt_str_expand_tabs(str, &len, 4);
+    TEST_CHECK_STR_EQ(result, str);
+    FREE(&result);
+  }
+  {
+    size_t len = 5;
+    char *str = mutt_str_dup("ap\tle");
+    char *result = mutt_str_expand_tabs(str, &len, 4);
+    TEST_CHECK_STR_EQ(result, "ap    le");
```
[the remark this answers is not in the document]
Comment (roccoblues) [reply test/string/mutt_str_expand_tabs.c:54]: Hey this is still a draft - no peeking. 😄 

> Before 	After
> `\tapple` 	`....apple`
> `X\tapple` 	`X...apple`
> `XX\tapple` 	`XX..apple`
> `XXX\tapple` 	`XXX.apple`
> `XXXX\tapple` 	`XXXX....apple`
> `XXXXX\tapple` 	`XXXXX...apple`

Thanks! I wanted to add way more tests next and those will come handy.

File: compose/preview.c [hunk 2]
```diff
@@ -181,6 +181,8 @@ static void draw_preview(struct MuttWindow *win, struct PreviewWindowData *wdata
 
       content_lines++;
 
+      line = mutt_str_expand_tabs(line, &line_len, 4);
```
Comment (roccoblues) [inline compose/preview.c:184]: Do we want to constant the 4 here? Or even use another value (please not 😄).

**Comment by christian-heusel** [comment]
This MR addresses the issue from #4534, so it works for me:
image

Thanks for coming up with a fix so quickly! 🎉

**Comment by roccoblues** [comment]
Thanks for giving it a try to quickly!

**Comment by gahr** [comment]
How about doing that in mutt_file_read_line using a new ReadLineFlags?

**Comment by roccoblues** [comment]
> How about doing that in mutt_file_read_line using a new ReadLineFlags?

Interesting idea. I guess it depends on wether we ever want to change the tab width value?

**Comment by gahr** [comment]
> > How about doing that in mutt_file_read_line using a new ReadLineFlags?
> 
> Interesting idea. I guess it depends on wether we ever want to change the tab width value?

I guess if we do, we'd make it into a config, and `mutt_file_read_line` could read from it

File: compose/preview.c (hunk 2 above)
Comment (flatcap) [reply compose/preview.c:184]: Sorry, it really needs to be 8.
That's the default in terminals and that's how it's hard-coded in the Pager.

**Comment by flatcap** [comment]
> > > How about doing that in mutt_file_read_line using a new ReadLineFlags?
> >
> > Interesting idea. I guess it depends on wether we ever want to change the tab width value?
> 
> I guess if we do, we'd make it into a config, and `mutt_file_read_line` could read from it

Hmm...
If the tab-size is hard-coded, perhaps,
but I don't want to see config creeping into library functions.

**Comment by gahr** [comment]
> > > > How about doing that in mutt_file_read_line using a new ReadLineFlags?
> > > 
> > > 
> > > Interesting idea. I guess it depends on wether we ever want to change the tab width value?
> > 
> > 
> > I guess if we do, we'd make it into a config, and `mutt_file_read_line` could read from it
> 
> Hmm... If the tab-size is hard-coded, perhaps, but I don't want to see config creeping into library functions.

Sure, let's go with a fixed 8-chars expansion

**Comment by roccoblues** [comment]
Sorry I lost track here. Is this fine now or should I move the tab expansion into `mutt_file_read_line()`?

**Review by flatcap — APPROVED** [review]
All good, thanks! (Sorry for the slow response (lost in my own world :-)
