### PR TITLE
Fix memory leak in tag-transforms and tag-formats

### LINKED ISSUE #3324: Memory leak in parse_tag_transforms
## Expected Behaviour

Running neomutt with `--asan` should not report any memory leaks.

## Actual Behaviour

```
==148887==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 37 byte(s) in 4 object(s) allocated from:
    #0 0x7f5e37922319 in __interceptor_strdup /usr/src/debug/gcc/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x55db3aec0661 in mutt_str_dup mutt/string.c:255
    #2 0x55db3ab64cef in parse_tag_transforms /usr/src/debug/neomutt/command_parse.c:1417
    #3 0x55db3aba3dd0 in mutt_parse_rc_buffer /usr/src/debug/neomutt/init.c:1019
    #4 0x55db3ab5d189 in source_rc /usr/src/debug/neomutt/command_parse.c:219
    #5 0x55db3aba2ea7 in mutt_init /usr/src/debug/neomutt/init.c:913
    #6 0x55db3abb7464 in main /usr/src/debug/neomutt/main.c:794
    #7 0x7f5e36f3b30f in __libc_start_call_main (/usr/lib/libc.so.6+0x2d30f)

Direct leak of 36 byte(s) in 4 object(s) allocated from:
    #0 0x7f5e37922319 in __interceptor_strdup /usr/src/debug/gcc/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x55db3aec0661 in mutt_str_dup mutt/string.c:255
    #2 0x55db3ab6471a in parse_tag_formats /usr/src/debug/neomutt/command_parse.c:1378
    #3 0x55db3aba3dd0 in mutt_parse_rc_buffer /usr/src/debug/neomutt/init.c:1019
    #4 0x55db3ab5d189 in source_rc /usr/src/debug/neomutt/command_parse.c:219
    #5 0x55db3aba2ea7 in mutt_init /usr/src/debug/neomutt/init.c:913
    #6 0x55db3abb7464 in main /usr/src/debug/neomutt/main.c:794
    #7 0x7f5e36f3b30f in __libc_start_call_main (/usr/lib/libc.so.6+0x2d30f)

Direct leak of 17 byte(s) in 4 object(s) allocated from:
    #0 0x7f5e37922319 in __interceptor_strdup /usr/src/debug/gcc/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x55db3aec0661 in mutt_str_dup mutt/string.c:255
    #2 0x55db3ab64d6c in parse_tag_transforms /usr/src/debug/neomutt/command_parse.c:1422
    #3 0x55db3aba3dd0 in mutt_parse_rc_buffer /usr/src/debug/neomutt/init.c:1019
    #4 0x55db3ab5d189 in source_rc /usr/src/debug/neomutt/command_parse.c:219
    #5 0x55db3aba2ea7 in mutt_init /usr/src/debug/neomutt/init.c:913
    #6 0x55db3abb7464 in main /usr/src/debug/neomutt/main.c:794
    #7 0x7f5e36f3b30f in __libc_start_call_main (/usr/lib/libc.so.6+0x2d30f)

Direct leak of 12 byte(s) in 4 object(s) allocated from:
    #0 0x7f5e37922319 in __interceptor_strdup /usr/src/debug/gcc/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x55db3aec0661 in mutt_str_dup mutt/string.c:255
    #2 0x55db3ab64797 in parse_tag_formats /usr/src/debug/neomutt/command_parse.c:1383
    #3 0x55db3aba3dd0 in mutt_parse_rc_buffer /usr/src/debug/neomutt/init.c:1019
    #4 0x55db3ab5d189 in source_rc /usr/src/debug/neomutt/command_parse.c:219
    #5 0x55db3aba2ea7 in mutt_init /usr/src/debug/neomutt/init.c:913
    #6 0x55db3abb7464 in main /usr/src/debug/neomutt/main.c:794
    #7 0x7f5e36f3b30f in __libc_start_call_main (/usr/lib/libc.so.6+0x2d30f)

SUMMARY: AddressSanitizer: 102 byte(s) leaked in 16 allocation(s).
```

## Steps to Reproduce

- Clone https://github.com/sheoak/neomutt-powerline-nerdfonts
- Run `neomutt -F powerline.neomuttrc`
- Close neomutt immediately

## How often does this happen?

- Always

## When did it start to happen?

- Dunno, only started using `--asan` to track down a (possibly related?) segfault.

## NeoMutt Version

```
NeoMutt 20211029-522-1cbc9a
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.16.12-arch1-1 (x86_64)
ncurses: ncurses 6.3.20211021 (compiled with 6.3.20211021)
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.17.1
OpenSSL: OpenSSL 1.1.1m  14 Dec 2021
libnotmuch: 5.6.0
storage: kyotocabinet, gdbm, lmdb

Configure options: --asan --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -fvar-tracking-assignments -fdebug-prefix-map=/home/florian/tmp/neomutt-git/src=/usr/src/debug -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR -fsanitize=address -O0 -fno-omit-frame-pointer -fno-common

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme +gss 
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

Devel options:
  asan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info
 
On Archlinux.  Also happens on 20211029.

### PR DESCRIPTION
**Pull request by gahr**
Also, I refactored the code to parse tag-transforms and tag-formats,
which was basically identical except for the hash table used, and I
moved TagFormats from globals into email/tags.h

**TODO**
- [x] figure why we [can't](https://github.com/neomutt/neomutt/blob/bbb669e4a89767746119706281dece19ee301d07/command_parse.c#L1382-L1388) register the same transform / format for two different tags, e.g. `tag-transform important STAR starred STAR`

Fixes #3324

### CODE REVIEW

File: command_parse.c [hunk 1]
```diff
@@ -1359,81 +1359,58 @@ enum CommandResult parse_subscribe_to(struct Buffer *buf, struct Buffer *s,
 #endif
 
 /**
- * parse_tag_formats - Parse the 'tag-formats' command - Implements Command::parse() - @ingroup command_parse
+ * parse_tag_mapping - Parse a 'tag-formats' or 'tag-transforms' command.
  */
-enum CommandResult parse_tag_formats(struct Buffer *buf, struct Buffer *s,
-                                     intptr_t data, struct Buffer *err)
+static enum CommandResult parse_tag_mapping(struct Buffer *s,
+                                            struct HashTable *ht, const char *what)
```
Comment (Austin-Ray) [inline command_parse.c:1365]: `ht` doesn't describe the hash table's purpose. Could we rename it along the lines of `tag_replacements` to make it obvious?

Similarly `what` could use a better name as it's name is unintuitive without reading its callers. It's datatype could also be constrained. Any objections to use an enum instead?

File: command_parse.c [hunk 2]
```diff
@@ -1359,81 +1359,58 @@ enum CommandResult parse_subscribe_to(struct Buffer *buf, struct Buffer *s,
...
       continue;
 
-    mutt_extract_token(buf, s, MUTT_TOKEN_NO_FLAGS);
-    format = mutt_str_dup(buf->data);
+    mutt_extract_token(map, s, MUTT_TOKEN_NO_FLAGS);
+    const char *key = mutt_buffer_string(map);
 
     /* avoid duplicates */
-    tmp = mutt_hash_find(TagFormats, format);
+    const char *tmp = mutt_hash_find(ht, map->data);
```
Comment (Austin-Ray) [inline command_parse.c:1383]: Let's use `key` here since we already have it.

**Review by Austin-Ray — CHANGES_REQUESTED** [review]
> figure why we [can't](https://github.com/neomutt/neomutt/blob/bbb669e4a89767746119706281dece19ee301d07/command_parse.c#L1382-L1388) register the same transform / format for two different tags, e.g. tag-transform important STAR starred STAR

The mapping is going the wrong way. It's implemented as `map`->`tag` so `STAR` ends up as the key. The variable names tripped me up while reading the code. Let's rename to something like `target` and `replacement`  to clarify the relationship.

---

Here's a diff that works on my machine:
```diff
diff --git a/command_parse.c b/command_parse.c
index 074d2db1e..1265bd2b7 100644
--- a/command_parse.c
+++ b/command_parse.c
@@ -1377,17 +1377,17 @@ static enum CommandResult parse_tag_mapping(struct Buffer *s,
       continue;

     mutt_extract_token(map, s, MUTT_TOKEN_NO_FLAGS);
-    const char *key = mutt_buffer_string(map);
+    const char *key = mutt_buffer_string(tag);

     /* avoid duplicates */
-    const char *tmp = mutt_hash_find(ht, map->data);
+    const char *tmp = mutt_hash_find(ht, tag->data);
     if (tmp)
     {
       mutt_debug(LL_DEBUG3, "tag %s '%s' already registered as '%s'\n", what, key, tmp);
       continue;
     }

-    mutt_hash_insert(ht, key, mutt_str_dup(mutt_buffer_string(tag)));
+    mutt_hash_insert(ht, key, mutt_str_dup(mutt_buffer_string(map)));
   }

   mutt_buffer_pool_release(&tag);
```

**Comment by gahr** [comment]
> > figure why we [can't](https://github.com/neomutt/neomutt/blob/bbb669e4a89767746119706281dece19ee301d07/command_parse.c#L1382-L1388) register the same transform / format for two different tags, e.g. tag-transform important STAR starred STAR
> 
> The mapping is going the wrong way. It's implemented as `map`->`tag` so `STAR` ends up as the key. The variable names tripped me up while reading the code. Let's rename to something like `target` and `replacement` to clarify the relationship.

Right! It took me a while to figure this out *after* reading your comment: the thing is, TagTransforms maps tags to transforms, while TagFormats maps formats to tags.

I'll open a fresh PR :)

**Comment by gahr** [comment]
Simple config to test this:
```
:tag-formats pgp GP
:tag-transform pgp P
:set index_format="%?GP?%GP& ?$index_format"
:push ":exec modify-labels<enter>pgp<enter>"
```
See a 'P' appear in the first column.

**Review by flatcap — COMMENTED** [review]
Rebased, tweaked couple of doxy comments

**Review by flatcap — APPROVED** [review]
Lovely, that's much tidier.

I like the warnings, but I've moved them out of the PR into [[devel/tt-warning]](https://github.com/neomutt/neomutt/tree/devel/tt-warning),
because I've frozen the strings to allow the translators to do their work.

We can merge them after the release,
(or you can apologise to the translators ;-)
