### PR TITLE
cmd_parse_fetch: debug: avoid NULL dereference

### LINKED ISSUE #4677: 20250905: core dump in imap code
## NeoMutt Version

```
NeoMutt 20250905
Copyright (C) 2015-2025 Richard Russon and friends
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: NetBSD 11.99.2 (amd64)
ncurses: ncurses 6.5.20240427 (compiled with 6.5.20240427)
libidn2: 2.3.7 (compiled with 2.3.7)
GPGME: 1.24.3
OpenSSL: OpenSSL 3.5.1 1 Jul 2025
libnotmuch: 5.6.0
storage: tokyocabinet

Configure options: --prefix=/usr/pkg --mandir=/usr/pkg/man --with-gss=/usr --with-ncurses=/usr/pkg --with-sasl=/usr/pkg --with-ssl=/usr --smime --tokyocabinet --disable-gdbm --disable-bdb --gpgme --notmuch --disable-lua

Compilation CFLAGS: -O2 -g -fstack-clash-protection -I/usr/include/krb5 -I/usr/include -I/usr/pkg/include/ncurses -I/usr/pkg/include -I/usr/pkg/include/glib-2.0 -I/usr/pkg/include/gio-unix-2.0 -I/usr/pkg/lib/glib-2.0/inc
lude -I/usr/pkg/include/python3.13 -std=c11 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -D_XOPEN_SOURCE_EXTENDED -DNCURSES_WIDECHAR

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls +gpgme
  -gsasl +gss +hcache -homespool +idn -inotify -locales_hack -lua +nls +notmuch
  +openssl +pgp +regex +sasl +smime -sqlite +truecolor

MAILPATH="/var/mail"
PKGDATADIR="/usr/pkg/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/pkg/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Expected Behaviour

Just reading email, nothing in particular, via IMAP.

## Actual Behaviour

It dumped core.

If NeoMutt crashed, did your OS create a 'coredump' file?

Yes, the backtrace is:
```
#0  0x0000000000aaa408 in cmd_parse_fetch (s=0x7d7b6d106802 "1 FETCH (UID 109313 FLAGS (\\Seen))", adata=0x7d7b6dbabbe0) at imap/command.c:430
430       mutt_debug(LL_DEBUG2, "Message UID %u updated\n", imap_edata_get(e)->uid);
(gdb) bt
#0  0x0000000000aaa408 in cmd_parse_fetch (s=0x7d7b6d106802 "1 FETCH (UID 109313 FLAGS (\\Seen))", adata=0x7d7b6dbabbe0) at imap/command.c:430
#1  cmd_handle_untagged (adata=0x7d7b6dbabbe0) at imap/command.c:1035
#2  imap_cmd_step (adata=adata@entry=0x7d7b6dbabbe0) at imap/command.c:1186
#3  0x0000000000ab1be2 in read_headers_normal_eval_cache (adata=adata@entry=0x7d7b6dbabbe0, msn_end=msn_end@entry=17624, uid_next=<optimized out>, store_flag_updates=false, eval_condstore=eval_condstore@entry=false)
    at imap/message.c:723
#4  0x0000000000ab23eb in imap_read_headers (m=m@entry=0x7d7b6d8e8600, msn_begin=msn_begin@entry=1, msn_end=msn_end@entry=17624, initial_download=initial_download@entry=true) at imap/message.c:1420
#5  0x0000000000aaeefe in imap_mbox_open (m=0x7d7b6d8e8600) at imap/imap.c:2060
#6  0x00000000009edb09 in mx_mbox_open (m=0x7d7b6d8e8600, flags=flags@entry=0 '\000') at mx.c:372
#7  0x00000000009f6b27 in change_folder_mailbox (menu=0x7d7b6d0e17c0, m=<optimized out>, oldcount=oldcount@entry=0x7d7b6d0e6584, shared=shared@entry=0x7d7b6d1d6070, read_only=read_only@entry=false)
    at index/dlg_index.c:692
#8  0x00000000009fe3bc in op_main_change_folder (shared=0x7d7b6d1d6070, priv=0x7d7b6d0e6580, op=<optimized out>) at index/functions.c:1125
#9  0x0000000000a01b4f in index_function_dispatcher (win=<optimized out>, op=op@entry=141) at index/functions.c:3280
#10 0x0000000000a09118 in dlg_pager (pview=pview@entry=0x7f7fff8f57a0) at pager/dlg_pager.c:522
#11 0x0000000000a0c8e2 in mutt_display_message (win_index=0x7d7b6dbae200, shared=shared@entry=0x7d7b6d1d6070) at pager/message.c:490
#12 0x00000000009ffa86 in op_display_message (shared=0x7d7b6d1d6070, priv=0x7d7b6d0e6580, op=<optimized out>) at index/functions.c:651
#13 0x0000000000a01b4f in index_function_dispatcher (win=<optimized out>, op=op@entry=74) at index/functions.c:3280
#14 0x00000000009f79da in dlg_index (dlg=<optimized out>, m_init=<optimized out>) at index/dlg_index.c:1371
#15 0x0000000000afc3dc in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at main.c:1758
(gdb) p e
$1 = (struct Email *) 0x7d7b69dd1ca0
(gdb) p *e
$2 = {security = 0, expired = false, flagged = false, mime = false, old = false, read = true, replied = false, superseded = false, trash = false, zhours = 0, zminutes = 0, zoccident = false, date_sent = 1735695551,
  received = 1735695557, lines = 0, sequence = 356576, env = 0x0, body = 0x0, path = 0x0, offset = 0, tags = {stqh_first = 0x0, stqh_last = 0x7d7b69dd1ce8}, notify = 0x0, edata = 0x0, active = true, changed = false,
  deleted = false, purge = false, edata_free = 0xaab828 <imap_edata_free>, nm_edata = 0x0, attach_del = false, attach_valid = false, display_subject = true, matched = false, quasi_deleted = false, recip_valid = false,
  searched = false, subject_changed = true, tagged = false, threaded = false, index = 109313, msgno = 0, attr_color = 0x0, score = 0, vnum = 0, attach_total = 0, recipient = 0, thread = 0x0, collapsed = false,
  visible = true, limit_visited = false, num_hidden = 0, tree = 0x0}
```
## How often does this happen?

- Sometimes

Twice so far, I think, but I didn't check the core dump the first time.

## When did it start to happen?

I think when upgraded to 20250905.

## Extra Info

* NetBSD 11.99.2/x86_64
* Were you using multiple copies of NeoMutt at once? I don't think so.
* Were you using 'screen' or 'tmux'? tmux, yes.
* Is your email local (maildir) or remote (IMAP)? IMAP

### PR DESCRIPTION
**Pull request by ThomasAdam**
When calling mutt_debug(), the passed in value to imap_edata_get() shouldn't be NULL, otherwise NULL will be dereferenced from the returned value, causing neomutt to crash.

Fixes #4677

### CODE REVIEW

**Comment by gahr** [comment]
This is checked just a couple of lines above

**Comment by gahr** [comment]
Ah, I think you meant to check the return of `imap_edata_get(e)`, not `e` itself.

**Comment by ThomasAdam** [comment]
> Ah, I think you meant to check the return of `imap_edata_get(e)`, not `e` itself.

How embarrassing.  You're entirely correct.  I have several patches in one place and incorrectly collated changes together.  Hopefully this change helps.

File: imap/command.c [hunk 1]
```diff
@@ -427,7 +427,12 @@ static void cmd_parse_fetch(struct ImapAccountData *adata, char *s)
     return;
   }
 
-  mutt_debug(LL_DEBUG2, "Message UID %u updated\n", imap_edata_get(e)->uid);
+  struct ImapEmailData *ied = imap_edata_get(e);
+  if (ied)
+  {
+    mutt_debug(LL_DEBUG2, "Message UID %u updated\n", ied->uid);
```
Comment (flatcap) [inline imap/command.c]: Hello stranger :-)
Thanks for the fix.

Just a small tweak.
By convention all `EmailData` vars are called `edata`.

```suggestion
  struct ImapEmailData *edata = imap_edata_get(e);
  if (edata)
  {
    mutt_debug(LL_DEBUG2, "Message UID %u updated\n", edata->uid);
```
