### PR TITLE
notmuch: open database with user's configuration

### LINKED ISSUE #3017: Neomutt slow and trying to parse an incorrect file
## Expected Behaviour

Neomutt should open and be responsive in a reasonable amount of time.

## Actual Behaviour

When opening neomutt it hangs for a long time (~1 minute). When I tried to debug with `-d6` I see that it is trying to load files that do not exist and takes a long time to open my notmuch database. A section of the log:

```
[2021-08-04 20:54:24]<1> nm_mbox_open() nm: reading messages...[current count=0]
[2021-08-04 20:54:24]<2> nm_db_get_filename() nm: db filename '/Users/blake/.local/share/notmuch/database'
[2021-08-04 20:54:24]<1> nm_db_do_open() nm: db open '/Users/blake/.local/share/notmuch/database' [READ] (timeout 5)
[2021-08-04 20:54:29]<2> get_query_string() nm: true
[2021-08-04 20:54:29]<2> windowed_query_from_query() nm: query:new
[2021-08-04 20:54:29]<2> query_window_reset() entering
[2021-08-04 20:54:29]<2> get_query_string() nm: query (windowed) 'query:new'
[2021-08-04 20:54:29]<2> get_query() nm: query successfully initialized (query:new)
[2021-08-04 20:54:29]<2> append_message() nm: appending message, i=0, id=35c557f5-0626-43a4-b2d3-b7e3f90c3145@dfw1s10mta453.xt.local, path=/Users/blake/.local/share/notmuch/database/<addr>/[Gmail].All Mail/cur/1628016054.53070_4.tea-rex,U=171935:2,
[2021-08-04 20:54:29]<1> append_message() nm: failed to parse message: /Users/blake/.local/share/notmuch/database/<addr>/[Gmail].All Mail/cur/1628016054.53070_4.tea-rex,U=171935:2,
```
I think there are two issues, first it takes a long time to open the database and secondly the file it is trying to load has the wrong path. I suspect neomutt is getting confused because my `folder` (`~/Email`) and `nm_default_url` (`~/.local/share/notmuch/database`) point to different locations and it is choosing to look for email under my `nm_default_url` path instead of `folder`. So when it should actually be loading from `~/Email/` instead of from `~/.local/share/notmuch/database`. 

Some snippets of my configs that may help.

### Notmuch config

```
database.backup_dir=.local/share/notmuch/backups
database.mail_root=/Users/blake/Email
database.path=/Users/blake/.local/share/notmuch/database
```

### Neomutt config

```
set nm_default_url = "notmuch:///Users/blake/.local/share/notmuch/database"
set folder = "~/Email"
```

## Steps to Reproduce

I think using neomutt with notmuch and having `folder` and `nm_default_url` separate will cause the issue.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded to: `20210205` and notmuch version `0.32.2` and moved my notmuch database away from where I keep emails.

## NeoMutt Version

```
NeoMutt 20210205
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Darwin 18.7.0 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libiconv: 1.11
libidn: 1.37 (compiled with 1.37)
GPGME: 1.16.0-unknown
OpenSSL: OpenSSL 1.1.1k  25 Mar 2021
libnotmuch: 5.3.0
storage: lmdb
compression: zlib

Configure options: --prefix=/nix/store/hjaa3153mhvy0b5ygzif384asq2q5shs-neomutt-20210205 --enable-autocrypt --gpgme --gss --lmdb --notmuch --ssl --sasl --with-homespool=mailbox --with-mailpath= --disable-include-path-in-cflags ac_cv_path_SENDMAIL=sendmail --zlib

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen -futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache +homespool +idn -inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl 
  +smime +sqlite +start_color +sun_attachment +typeahead 
MAILPATH="mailbox"
PKGDATADIR="/nix/store/hjaa3153mhvy0b5ygzif384asq2q5shs-neomutt-20210205/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/nix/store/hjaa3153mhvy0b5ygzif384asq2q5shs-neomutt-20210205/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version `OSX 10.14`
* Were you using multiple copies of NeoMutt at once? `No`
* Were you using 'screen' or 'tmux'? `No`
* Is your email local (maildir) or remote (IMAP)? `local`

### PR DESCRIPTION
**Pull request by Austin-Ray**
Notmuch 0.32 introduced a new database open function that allows using
the user's configuration. With libnotmuch using the user's
configuration, the notmuch backend behaves more like the notmuch CLI. It
will exclude tags defined in `.notmuch-config`, correct file paths for
split database and email directory setups, and allow notmuch saved
queries.

The new function call is wrapped behind a libnotmuch version check or if
libnotmuch provides the new method. Notmuch 0.32-0.32.2 didn't bump the
version number so it incorrectly reports 5.3. The version number will be
fixed in notmuch 0.32.3.

* **What are the relevant issue numbers?**

Fixes #3017

### CODE REVIEW

File: notmuch/db.c [hunk 1]
```diff
@@ -119,7 +119,10 @@ notmuch_database_t *nm_db_do_open(const char *filename, bool writable, bool verb
 
   do
   {
-#if LIBNOTMUCH_CHECK_VERSION(4, 2, 0)
+#if LIBNOTMUCH_CHECK_VERSION(5, 4, 0) || defined(HAVE_NOTMUCH_DATABASE_OPEN_WITH_CONFIG)
```
Comment (gahr) [inline notmuch/db.c:122]: Isn't `HAVE_NOTMUCH_DATABASE_OPEN_WITH_CONFIG` enough?

**Comment by Austin-Ray** [comment]
> > @@ -119,7 +119,10 @@ notmuch_database_t *nm_db_do_open(const char *filename, bool writable, bool verb
>  
>    do
>    {
> -#if LIBNOTMUCH_CHECK_VERSION(4, 2, 0)
> +#if LIBNOTMUCH_CHECK_VERSION(5, 4, 0) || defined(HAVE_NOTMUCH_DATABASE_OPEN_WITH_CONFIG)
> 
> Isn't `HAVE_NOTMUCH_DATABASE_OPEN_WITH_CONFIG` enough?

Yes for accessing the function.

Though the version check makes it easier to see where and how NeoMutt
uses libnotmuch. This is useful for debugging across libnotmuch versions
and new contributors who may be familiar with the macro.

For example, grepping:
 - "NOTMUCH" returns 187 results with lots of false positives from
   MUTT_NOTMUCH mailbox type
 - "HAVE_NOTMUCH" returns 6 results
 - "LIBNOTMUCH_CHECK_VERSION" returns 15 results 

This makes it easier to see where we handle multiple versions of
libnotmuch. Since the extra conditional's low cost occurs at compile
time, I think the benefit of easier codebase navigation is worth it.

**Comment by gahr** [comment]
I am little convinced that "Though the version check makes it easier to see where and how NeoMutt
uses libnotmuch." applies especially to `notmuch/db.c` , and I think the version check conveys the wrong message in this case. But I'm not going to fight this :)

**Review by flatcap — APPROVED** [review]
