### PR TITLE
fix: prevent timezone overflow

### LINKED ISSUE #819: Integer overflow in mutt_parse_date()
On 32-bit systems, signed integer overflow in `mutt_parse_date()` is possible.
To reproduce, build NeoMutt with `-fsanitize=undefined` and run:

    $ printf '\1\1\1\1\nDate: 0 Nov 0 0:0 +0060\n' > intoverflow.mmdf
    $ export UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_stacktrace=1
    $ neomutt -R -f intoverflow.mmdf 2>&1 >/dev/null | cat
    lib/date.c:592:31: runtime error: signed integer overflow: -2147483648 + -3600 cannot be represented in type 'long int'
        #0 0x802c922f in mutt_parse_date lib/date.c:592
        #1 0x8025ae4b in mutt_parse_rfc822_line .../neomutt/parse.c:839
        #2 0x8025cb35 in mutt_read_rfc822_header .../neomutt/parse.c:1243
        #3 0x80208089 in mmdf_parse_mailbox .../neomutt/mbox.c:175
        #4 0x80208f47 in mbox_open_mailbox .../neomutt/mbox.c:460
        #5 0x8022a5d7 in mx_open_mailbox .../neomutt/mx.c:480
        #6 0x80202ff4 in main .../neomutt/main.c:929
        #7 0xb701e285 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18285)
        #8 0x8015cf70  (.../neomutt/neomutt+0x6bf70)

Tested with git master (b97206f1a76480e03f27ca32df44b2caef950e73).

Found using [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/).

### LINKED ISSUE #820: Integer overflow in mbox_parse_mailbox()
On 32-bit systems with non-UTC timezones, signed integer overflow in `mbox_parse_mailbox()` is possible.
To reproduce, build NeoMutt with `-fsanitize=undefined` and run:

    $ printf 'From Mon Jan 1 0:0 1901\n' > intoverflow.mbox
    $ export TZ=Europe/Warsaw
    $ export UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_stacktrace=1
    $ neomutt -R -f intoverflow.mbox 2>&1 >/dev/null | cat
    mbox.c:317:28: runtime error: signed integer overflow: -2147483648 - 5040 cannot be represented in type 'long int'
        #0 0x801b7643 in mbox_parse_mailbox .../neomutt/mbox.c:317
        #1 0x801b9f1c in mbox_open_mailbox .../neomutt/mbox.c:458
        #2 0x801db5d7 in mx_open_mailbox .../neomutt/mx.c:480
        #3 0x801b3ff4 in main .../neomutt/main.c:929
        #4 0xb7015285 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18285)
        #5 0x8010df70  (.../neomutt/neomutt+0x6bf70)

Tested with git master (b97206f1a76480e03f27ca32df44b2caef950e73).

Found using [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/).

### PR DESCRIPTION
**Pull request by flatcap**
On 32-bit arches it's easy to over-/under-flow the date.
We replace these with the max/min values allowed in a time_t.

When we encounter one of these dates, pretend it's UTC to prevent another overflow.

Fixes #819
Fixes #820

### CODE REVIEW

File: lib/date.c [hunk 1]
```diff
@@ -588,5 +592,10 @@ time_t mutt_parse_date(const char *s, struct Tz *tz_out)
     tz_out->zoccident = zoccident;
   }
 
-  return (mutt_mktime(&tm, 0) + tz_offset);
+  time_t time = mutt_mktime(&tm, 0);
+  /* Check we haven't overflowed the time (on 32-bit arches) */
+  if ((time != TIME_T_MAX) && (time != TIME_T_MIN))
+    time += tz_offset;
```
Comment (gahr) [inline lib/date.c]: Could we possibly overflow after the addition? Just asking...

Comment (flatcap) [reply lib/date.c]: Absolutely.  It's now a game of 'whack-a-mole'.

I think we're probably OK.
Once we have the email's date in the correct timezone, then we're unlikely to alter it.
(I haven't checked this is true).

I chose `TIME_T_MIN`, `TIME_T_MAX` to better represent the extreme dates.
The alternative is to represent all out-of-range dates as 1970-01-01.
