### PR TITLE
Devel/mailsize expandos

### LINKED ISSUE #1925: index_format %c reports wrong sizes
## Expected Behaviour
* Look in NeoMutt's index at an email that is 618 bytes.
* In previous versions of NeoMutt (e.g. b6a602e8a), the correct size is displayed, i.e. `618`.

## Actual Behaviour
* In NeoMutt 20191102, the wrong size is displayed, i.e. `5.5k`.

## Steps to Reproduce
Include `%c` in `index_format`, e.g.
```
set index_format="%4C %Z│%[%a %e %b %y %l:%M%P]│%-15.15L│%4c│%s"
```
Open NeoMutt and compare sizes between versions.

## More information
* I have also confirmed that the email is indeed the smaller size reported in the older version.
* The couple of emails I tested are not multipart, but plain text.

## How often does this happen?
In 19/20 emails that I checked, the size reported in the buggy version is larger.

## When did it start to happen?

- When I upgraded from unstable b6a602e8a to stable 20191102. (I also tried the latest 6a0e1814a, and the bug is there too.)

I'm happy to git bisect if necessary, but just wanted some feedback first in case this was already known or a dupe.

## NeoMutt Version

```
PUT YOUR "neomutt -v" OUTPUT HERE
NeoMutt 20191102
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.3.7-arch1-2-ARCH (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.2.0 (compiled with 2.2.0)
GPGme: 1.13.1
hcache backends: kyotocabinet, gdbm, lmdb

Compiler:
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
gcc version 9.2.0 (GCC) 

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --enable-lua --notmuch --gss --ssl --sasl --with-ui=ncurses --with-idn2=/usr --idn=0 --idn2=1 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch +openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version: Arch Linux
* Were you using multiple copies of NeoMutt at once? No
* Were you using 'screen' or 'tmux'? No
* Is your email local (maildir) or remote (IMAP)? maildir

### PR DESCRIPTION
**Pull request by Amudtogal**
Add a %cr expando to index_format to list the full email size (including
header). The previous %c expando provides the size of the mail body
instead.

Closes #1925.

@neomutt/reviewers This is my first commit, I would be glad about a review! In particular, I am not sure whether I updated the documentation in every necessary place. It would be great, if someone more experienced could check that... Also, do I need to run the `makedoc` script manually or is this automated (I couldn't figure out, how to run it anyway)?

* **What does this PR do?**

Adds the specified expando.

* **Screenshots (if relevant)**

* **Does this PR meet the acceptance criteria?** (This is just a reminder for you,
  this section can be removed if you fulfill it.)

   - Documentation created/updated (you have to edit
     [doc/manual.xml.head](https://www.github.com/neomutt/neomutt/blob/master/doc/manual.xml.head)
     for that)

   - All builds and tests are passing

   - Added [doxygen code documentation](https://neomutt.org/dev/doxygen)
     [syntax](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html)

   - Code follows the [style guide](https://neomutt.org/dev/coding-style)

* **What are the relevant issue numbers?**
#1925

### CODE REVIEW

File: hdrline.c [hunk 1]
```diff
@@ -656,7 +657,15 @@ static const char *index_format_str(char *buf, size_t buflen, size_t col, int co
...
     case 'c':
       colorlen = add_index_color(buf, buflen, flags, MT_COLOR_INDEX_SIZE);
-      mutt_str_pretty_size(tmp, sizeof(tmp), email_size(e));
+      if (src[0] == 'r')
+      {
+        mutt_str_pretty_size(tmp, sizeof(tmp), email_size(e));
+        src++;
+      }
+      else
+      {
```
Comment (Austin-Ray) [inline hdrline.c]: We can probably simplify this with something like:

```C
...
size_t report_size = e->content->length;

if (src[0] == 'r')
{
    report_size = email_size(e);
    src++;
}

mutt_str_pretty_size(tmp, sizeof(tmp), report_size);
...
```

**Comment by flatcap** [comment]
The code looks good.  Thanks.

> whether I updated the documentation in every necessary place

Yes.
The C comment in `hdrline.c` will be processed by Doxygen and will appear [here](https://neomutt.org/code/hdrline_8c.html#a51ed1cee096de7c8d5c44708c7af90a8).
The C comment (in nroff format) in `init.h` will become [part of the docs](https://neomutt.org/guide/reference#index-format) for `$index_format`.
The DocBook XML manual is [converted into several formats](https://neomutt.org/images/make-docs.svg), including the web guide, e.g. [Index Colour](https://neomutt.org/feature/index-color).

> do I need to run the `makedoc` script manually or is this automated

It's run as part of the normal `make`.
You can check your work with `make validate-doc`

Getting from the source dir to the website is a complicated manual job that I perform.
