### PR TITLE
Fix static addr mbox to udomain

### LINKED ISSUE #1150: Eliminate static variable in mutt_addr_mbox_to_udomain()
This is an "easy" task ([find more](https://github.com/neomutt/neomutt/issues?q=label:"good%20first%20issue")) and it's open to everyone.  [_read more..._](https://neomutt.org/dev/easy-tasks)

## Description

`mutt_addr_mbox_to_udomain()` returns pointers into a static buffer.

### Part 2: Change the callers to `free()` the strings

There are three callers, all in `mutt/address.c` which will need changing.

### PR DESCRIPTION
**Pull request by psyomn**
Remove static function variable from function.

Fixes #1150

### CODE REVIEW

**Comment by psyomn** [comment]
I'm not sure how you folk feel about the tests I added, but I could go ahead and remove them if they're not unwanted. Read the docs, tried to stick to things as much as possible.

File: mutt/address.c [hunk 1]
```diff
@@ -930,23 +930,33 @@ bool mutt_addr_is_local(struct Address *a)
...
 {
-  static char *buf = NULL;
+  char *buf = NULL;
   char *p = NULL;
 
   mutt_str_replace(&buf, mbox);
-  if (!buf)
-    return -1;
+  if (!buf) goto fail;
+  if (strchr(buf, '@') - buf == 0) goto fail_cleanup;
```
Comment (gahr) [inline mutt/address.c]: I would prefer a solution where `strchr` is called only once. Once you get the result, you should be able to discriminate the four important cases:
1. `@` is not part of the string -> fail
2. the string starts with `@` -> fail
3. the string ends with `@` -> fail
3. the string contains `@` -> ok, split into `user` and `domain` part

Also, you should be able to exploit `mutt_str_substr_dup` to avoid copying the original `mbox` string twice, and get rid of `buf` altogether.

File: mutt/address.c [hunk 2]
```diff
@@ -998,11 +1008,14 @@ const char *mutt_addr_for_display(struct Address *a)
     return a->mailbox;
 
   local_mailbox = mutt_idna_intl_to_local(user, domain, MI_MAY_BE_IRREVERSIBLE);
+
   if (!local_mailbox)
     return a->mailbox;
```
Comment (gahr) [inline mutt/address.c]: You're leaking `user` and `domain` here. Please free them as soon as you're done using them.

**Comment by psyomn** [comment]
Thanks for the feedback, I've applied the changes you requested. I'll try and go over this one more time tomorrow.

File: mutt/address.c [hunk 3]
```diff
@@ -930,23 +930,22 @@ bool mutt_addr_is_local(struct Address *a)
...
+  char *ptr = strchr(mbox, '@');
+
+  if (ptr - mbox == 0) goto fail;
+  if (!ptr || !ptr[1]) goto fail;
 
-  mutt_str_replace(&buf, mbox);
-  if (!buf)
-    return -1;
+  *user = mutt_str_substr_dup(mbox, ptr);
+  *domain = mutt_str_substr_dup(ptr + 1, NULL);
```
Comment (gahr) [inline mutt/address.c]: `mutt_str_strdup(ptr + 1)` perhaps?

File: mutt/address.c [hunk 4]
```diff
@@ -930,23 +930,22 @@ bool mutt_addr_is_local(struct Address *a)
...
+ * @warning you must free user and domain
  */
 int mutt_addr_mbox_to_udomain(const char *mbox, char **user, char **domain)
 {
-  static char *buf = NULL;
-  char *p = NULL;
+  char *ptr = strchr(mbox, '@');
+
+  if (ptr - mbox == 0) goto fail;
+  if (!ptr || !ptr[1]) goto fail;
```
Comment (gahr) [inline mutt/address.c]: Can we please make it a bit clearer what the fail cases are? How about:

```c
/* Fail if '@' is nowehere, at start, or at end */
if (ptr == NULL || ptr == mbox || ptr[1] == '\0')
{
  goto fail;
}
```

File: mutt/address.c [hunk 5]
```diff
@@ -998,11 +997,17 @@ const char *mutt_addr_for_display(struct Address *a)
     return a->mailbox;
 
   local_mailbox = mutt_idna_intl_to_local(user, domain, MI_MAY_BE_IRREVERSIBLE);
-  if (!local_mailbox)
```
Comment (gahr) [inline mutt/address.c]: I would prefer `user` and `domain` to be freed as soon as they're not needed anymore, no matter whether `mutt_idna_intl_to_local` succeeded or not. What you do in `mutt_addrlist_to_intl` is better in my opinion.

File: test/address.c [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+        TEST_CHECK(mutt_addr_mbox_to_udomain("@nobobohnoez", &user, &domain) == -1) ||
+        TEST_CHECK(mutt_addr_mbox_to_udomain("", &user, &domain) == -1)) {
+      TEST_MSG("bad return");
+    }
+  }
+
+  { /* common */
+    int ret = 0;
+    char *str = calloc(256, sizeof(*str));
+    strcat(str, "bob@bobsdomain");
```
Comment (gahr) [inline test/address.c]: How about `const char *str = "bob@bobsdomain"` ?

File: test/address.c [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+    TEST_CHECK_STR_EQ("bobsdomain", domain);
+
+    FREE(&user);
+    FREE(&domain);
+    FREE(&str);
+  }
+
+  { /* integration */
+    size_t buflen = 256;
+    char *buf = calloc(buflen, sizeof(*buf));
```
Comment (gahr) [inline test/address.c]: How about `char buf[256]` ?

File: mutt/address.c (hunk 5 above)
Comment (psyomn) [reply mutt/address.c]: Done!

**Comment by psyomn** [comment]
Thanks for the feedback! I tried my best to apply the changes you suggested. Cheers!

**Comment by flatcap** [comment]
(@gahr's on holiday)

The code looks good.  Please can you run `clang-format -i` on the source files you've changed.
It'll move some `{}`s, and reindent, to match the other NeoMutt code.

I see a problem with one of the test cases, though.
```c
if (TEST_CHECK(addr_mbox_to_udomain("bobnodomain@", &user, &domain) == -1) ||
    TEST_CHECK(addr_mbox_to_udomain("bobnodomain", &user, &domain) == -1) ||
    TEST_CHECK(addr_mbox_to_udomain("@nobobohnoez", &user, &domain) == -1) ||
    TEST_CHECK(addr_mbox_to_udomain("", &user, &domain) == -1))
```

Do you see it?
Try changing the second line to a **valid** address and run the test.

**Comment by psyomn** [comment]
Hey sorry for not getting back to you sooner. It's been a little busy on my side. I'll try and contribute again to this repo; thank you for all the feedback you guys gave me along the way!
