### PR TITLE
Fix issue #849

### LINKED ISSUE #849: Virtual mailbox's notmuch URI ignores limit= parameter
* **bug reports**

    * Expected behavior
    Virtual mailboxes using notmuch queries should return the number of emails specified by the limit= parameter e.g. 1000 emails.

    * Actual behavior
    notmuch queries return all emails matching a query.

    * Steps to reproduce
      1. Setup virtual mailbox using notmuch's URI with limit= parameter
          * I am using: 
             > virtual-mailboxes "unified inbox"   "notmuch://?query=tag:inbox&limit=1000"
      2. Open virtual mailbox in neomutt
      3. Compare number of emails in mailbox to specified limit

    * Used program versions
      NeoMutt 20170912 (1.9.0)

    * Operating System and its version
      System: Linux 4.13.5-1-ARCH (x86_64)

Running neomutt with debug level 2 show this message in the log:

> [2017-10-12 23:35:06] Reading configuration file '/home/aray/.mutt/mailboxes'.
> [2017-10-12 23:35:06] nm_normalize_uri (notmuch://?query=tag:inbox&limit=1000)
> [2017-10-12 23:35:06] nm_normalize_uri #<span></span>1 () -> db_query: (null)
> [2017-10-12 23:35:06] nm: get_query_string(0)
> [2017-10-12 23:35:06] nm: query 'tag:inbox'
> [2017-10-12 23:35:06] nm_normalize_uri #<span></span>2 () -> db_query: tag:inbox
> [2017-10-12 23:35:06] nm_uri_from_query (tag:inbox)
> [2017-10-12 23:35:06] nm: db filename '/home/aray/.mail'
> [2017-10-12 23:35:06] nm: uri from query 'notmuch:///home/aray/.mail?type=messages&query=tag%3Ainbox'
> [2017-10-12 23:35:06] nm_normalize_uri #<span></span>3 (notmuch://?query=tag:inbox&limit=1000) -> notmuch:///home/aray/.mail?type=messages&query=tag%3Ainbox

Normalization seems to drop the limit= parameter.

Thanks for taking a look!

### PR DESCRIPTION
**Pull request by Austin-Ray**
nm_uri_from_query() checks if there is a custom limit and includes it
in the URI. This keeps the limit intact after nm_normalize_uri()
terminates. Otherwise, the limit is stored within nm_normalize_uri()'s
temporary NmCtxData struct and lost upon termination.

Additionally, nm_normalize_uri() properly initializes tmp_ctxdata, which
sets the default db_limit value. This ensures db_limit is either
NmDbLimit or the custom limit. My earlier attempt to resolve #849 did
not initialize db_limit and suffered from random db_limit values.

The url_parse_query() check was removed from nm_normalize_uri() as
new_ctxdata() contains the same block of code. Error message numbering
has been updated the reflect the change.

* **What does this PR do?**
Fixes issue #849
* **Are there points in the code the reviewer needs to double check?**
I am unsure if I need to free the NmCtxData struct in nm_normalize_uri(). I had tried using free_ctxdata(), but neomutt would segfault on start. 
* **Screenshots (if relevant)**
N/A
* **What are the relevant issue numbers?**
#849

### CODE REVIEW

File: mutt_notmuch.c [hunk 1]
```diff
@@ -1792,23 +1799,22 @@ bool nm_normalize_uri(char *new_uri, const char *orig_uri, size_t new_uri_sz)
   struct Context tmp_ctx;
   struct NmCtxData tmp_ctxdata;
 
-  tmp_ctx.magic = MUTT_NOTMUCH;
-  tmp_ctx.data = &tmp_ctxdata;
-  tmp_ctxdata.db_query = NULL;
+  struct NmCtxData *tmp_data_from_uri = new_ctxdata(strdup(orig_uri));
```
Comment (flatcap) [inline mutt_notmuch.c]: I can't see the need for this `strdup()`
Inside `new_ctxdata()` there are calls to `mutt_substrdup()` to keep the bits we want to keep.

Comment (Austin-Ray) [reply mutt_notmuch.c]: Without the `strdup()` I receive a discarded qualifier warning during compilation. Would casting it to `char *` be a better alternative?

Comment (gahr) [reply mutt_notmuch.c]: Not a good one :) How about changing `new_ctxdata` to take a `const char*`?

**Comment by gahr** [comment]
How about not using an additional temporary variable for the result of `new_ctxdata(orig_uri);` and instead assign it directly to `tmp_ctx.data`?

**Comment by gahr** [comment]
Here's the diff I propose against your branch:

```diff
diff --git a/mutt_notmuch.c b/mutt_notmuch.c
index daf21c0a..061fe596 100644
--- a/mutt_notmuch.c
+++ b/mutt_notmuch.c
@@ -334,7 +334,7 @@ static void free_ctxdata(struct NmCtxData *data)
  * A new nm_ctxdata struct is created, then the query is parsed and saved
  * within it.  This should be freed using free_ctxdata().
  */
-static struct NmCtxData *new_ctxdata(char *uri)
+static struct NmCtxData *new_ctxdata(const char *uri)
 {
   struct NmCtxData *data = NULL;

@@ -1797,38 +1797,38 @@ bool nm_normalize_uri(char *new_uri, const char *orig_uri, size_t new_uri_sz)
   char buf[LONG_STRING];

   struct Context tmp_ctx;
-  struct NmCtxData tmp_ctxdata;
+  struct NmCtxData *tmp_ctxdata = new_ctxdata(orig_uri);

-  struct NmCtxData *tmp_data_from_uri = new_ctxdata(strdup(orig_uri));
-
-  if (!tmp_data_from_uri) 
+  if (!tmp_ctxdata) 
     return false;

-  tmp_ctxdata = *tmp_data_from_uri;
-
   tmp_ctx.magic = MUTT_NOTMUCH;
-  tmp_ctx.data = &tmp_ctxdata;
+  tmp_ctx.data = tmp_ctxdata;

-  mutt_debug(2, "nm_normalize_uri #1 () -> db_query: %s\n", tmp_ctxdata.db_query);
+  mutt_debug(2, "nm_normalize_uri #1 () -> db_query: %s\n", tmp_ctxdata->db_query);

-  if (get_query_string(&tmp_ctxdata, false) == NULL)
+  if (get_query_string(tmp_ctxdata, false) == NULL)
   {
     mutt_error(_("failed to parse notmuch uri: %s"), orig_uri);
     mutt_debug(2, "nm_normalize_uri () -> error #1\n");
+    FREE(&tmp_ctxdata);
     return false;
   }

-  mutt_debug(2, "nm_normalize_uri #2 () -> db_query: %s\n", tmp_ctxdata.db_query);
+  mutt_debug(2, "nm_normalize_uri #2 () -> db_query: %s\n", tmp_ctxdata->db_query);

-  strfcpy(buf, tmp_ctxdata.db_query, sizeof(buf));
+  strfcpy(buf, tmp_ctxdata->db_query, sizeof(buf));

   if (nm_uri_from_query(&tmp_ctx, buf, sizeof(buf)) == NULL)
   {
     mutt_error(_("failed to parse notmuch uri: %s"), orig_uri);
     mutt_debug(2, "nm_normalize_uri () -> error #2\n");
+    FREE(&tmp_ctxdata);
     return true;
   }

+  FREE(&tmp_ctxdata);
+
   strncpy(new_uri, buf, new_uri_sz);

   mutt_debug(2, "nm_normalize_uri #3 (%s) -> %s\n", orig_uri, new_uri);
```

**Comment by Austin-Ray** [comment]
I have updated my branch with the suggested changes.

Thank you for the constructive feedback! It is a very beneficial learning experience for me. My skill level with C is novice at best.

**Comment by flatcap** [comment]
I've rebased your changes and added [a `memset()`](https://github.com/Austin-Ray/neomutt/blob/96997dc163bce218c65a1a3222f83d7b22e38dec/mutt_notmuch.c#L1804).

```c
struct Context tmp_ctx;
memset(&tmp_ctx, 0, sizeof(tmp_ctx));
```

We were calling `nm_uri_from_query()` with a mostly uninitialised `struct Context`.
If someone changed this function to use other members, it might crash.
