### PR TITLE
Fix line split logic in help

### LINKED ISSUE #1018: Help page badly rendered
## bug reports

The help page got broken by https://github.com/neomutt/neomutt/commit/9cda4e2549c01e7b7c8b34aa98f38c2328ced0cb#diff-081cf476dd9ac3b05c183570de47cb23L227

### PR DESCRIPTION
**Pull request by gahr**
Fixes #1018

### CODE REVIEW

File: help.c [hunk 1]
```diff
@@ -218,15 +218,15 @@ static void format_line(FILE *f, int ismacro, const char *t1, const char *t2, co
...
   int n;
 
   fputs(t1, f);
 
   /* don't try to press string into one line with less than 40 characters.
      The double parenthesis avoids a gcc warning, sigh ... */
-  split = MuttIndexWindow->cols;
-  if (split < 40)
+  split = (MuttIndexWindow->cols < 40);
+  if (split)
```
Comment (flatcap) [inline help.c]: Ah, good spot.  The original line was misleading.

File: help.c [hunk 2]
```diff
@@ -218,15 +218,15 @@ static void format_line(FILE *f, int ismacro, const char *t1, const char *t2, co
...
   int col;
   int col_a, col_b;
-  int split;
+  bool split;
   int n;
 
   fputs(t1, f);
 
   /* don't try to press string into one line with less than 40 characters.
      The double parenthesis avoids a gcc warning, sigh ... */
```
Comment (flatcap) [inline help.c]: We don't need the "double parenthesis" part any more.
