### PR TITLE
mx: ensure Mailbox is always added to Account->mailboxes

### LINKED ISSUE #1486: Segfault in imap_mbox_open
## Expected Behaviour

Run neomutt with my IMAP mailbox

## Actual Behaviour

```
(gdb) bt
#0  0x000055df732c8d29 in imap_mbox_open (m=0x55df74f8fca0, ctx=0x55df74f72f30) at imap/imap.c:1974
#1  0x000055df7326bcb0 in mx_mbox_open (m=<optimized out>, path=<optimized out>, flags=0) at mx.c:370
#2  0x000055df7325c671 in main (argc=1, argv=<optimized out>, envp=<optimized out>) at main.c:1201
```

If NeoMutt crashed, did your OS create a 'coredump' file?
yeah

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded
  Which version did you use to use?

Yesterday's master, i suppose?

## NeoMutt Version

```
NeoMutt 20180716-952-a2da0a
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.19.5 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn: 1.35 (compiled with 1.35)
GPGme: 1.12.0
hcache backends: bdb

Compiler:
Using built-in specs.
COLLECT_GCC=x86_64-pc-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/8.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-8.2.0-r4/work/gcc-8.2.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/8.2.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.2.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.2.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.2.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/8.2.0/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo Hardened 8.2.0-r4 p1.5' --enable-esp --enable-libstdcxx-time --disable-libstdcxx-pch --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libmudflap --disable-libssp --disable-libmpx --disable-systemtap --enable-vtable-verify --enable-libvtv --enable-lto --without-isl --enable-libsanitizer --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 8.2.0 (Gentoo Hardened 8.2.0-r4 p1.5) 

Configure options: --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --docdir=/usr/share/doc/neomutt-99999999 --libdir=/usr/lib64 --disable-doc --enable-nls --disable-notmuch --enable-gpgme --enable-pgp --disable-smime --enable-bdb --disable-gdbm --disable-kyotocabinet --disable-qdbm --disable-tokyocabinet --enable-idn --disable-gss --disable-lmdb --enable-sasl --with-ui=ncurses --sysconfdir=/etc/neomutt --enable-ssl --disable-gnutls

Compilation CFLAGS: -O2 -pipe -march=nehalem -mtune=ivybridge -Og -ggdb3 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include  -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens +getaddrinfo 
  -gnutls +gpgme -gss +hcache -homespool +idn +inotify -locales_hack -lua +meta 
  -mixmaster +nls -notmuch +openssl +pgp +sasl -smime +start_color 
  +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc/neomutt"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version
Gentoo
* Were you using multiple copies of NeoMutt at once?
no
* Were you using 'screen' or 'tmux'?
no
* Is your email local (maildir) or remote (IMAP)?
imap

### PR DESCRIPTION
**Pull request by sileht**
mx: share code between ac_find implementations
mx: Ensure mailbox is always added to Account->mailboxes

Fixes #1486

### CODE REVIEW

File: maildir/shared.c [hunk 1]
```diff
@@ -1700,17 +1700,8 @@ struct Account *maildir_ac_find(struct Account *a, const char *path)
  */
 int maildir_ac_add(struct Account *a, struct Mailbox *m)
 {
-  if (!a || !m)
+  if (!a || !m || m->magic != MUTT_MAILDIR)
```
Comment (Austin-Ray) [inline maildir/shared.c]: I'm reposting this since it appears GitHub did not want to link directly to the code:

The mh backend uses this function as well. We should expand the check to handle MUTT_MH.

It looks like this function had been broken since this guard clause was further down.

Comment (sileht) [reply maildir/shared.c]: Well catch, thx.
