### PR TITLE
Fix 2891

### LINKED ISSUE #2891: neomutt takes forever "Sorting mailbox..." on termux
## Expected Behaviour

Opening neomutt

## Actual Behaviour

Takes (seemingly) forever "Sorting mailbox..."
I waited for about 15 minutes on a mailbox that is about 500 messages.
No crash, though.

## Steps to Reproduce

* neomutt with notmuch
* in termux
* open neomutt without flags

## How often does this happen?

- Always

## When did it start to happen?

- When I setup neomutt on termux (never had it running before)

## NeoMutt Version

```
$ neomutt -v
NeoMutt 20210205
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 4.14.180-perf-g302b184 (aarch64)
ncurses: ncurses 6.2.20200725 (compiled with 6.2.20200725)
libiconv: 1.16
OpenSSL: OpenSSL 1.1.1i  8 Dec 2020
libnotmuch: 5.3.0
storage: gdbm
compression: zstd

Configure options: --host=aarch64-linux-android --prefix=/data/data/com.termux/files/usr --with-mailpath=/data/data/com.termux/files/usr/var/mail --notmuch --disable-gpgme --disable-idn --zstd --sasl --ssl --gdbm --gss

Compilation CFLAGS:  -fstack-protector-strong -Oz -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/data/data/com.termux/files/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme +gss +hcache -homespool -idn +inotify 
  -locales_hack -lua +meta -mixmaster +nls +notmuch +openssl +pgp +regex +sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/data/data/com.termux/files/usr/var/mail"
PKGDATADIR="/data/data/com.termux/files/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/data/data/com.termux/files/usr/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

> Operating System and its version

Android 10, termux from fdroid (up to date as of time of writing this)

> Were you using multiple copies of NeoMutt at once? 

No

> Were you using 'screen' or 'tmux'?

Reproducible with and without tmux. 

> Is your email local (maildir) or remote (IMAP)?

Local, notmuch.

---

If someone can guide me through the steps of debugging this, I'd love to help out! Maybe some termux-specific knowledge is required tho.

### PR DESCRIPTION
**Pull request by Austin-Ray**
Validates `nm_default_url` to ensure its in the correct form, and changes sleep time from 8.33 minutes to the correct 1/2 second.

~~Commit 22c5f2297 changed `nanosleep()` to `mutt_date_sleep_ms()`, but
didn't alter the valaue so a half second sleep became 8 minutes and 20
seconds.~~

* **What are the relevant issue numbers?**

Fixes #2891 

~~Partial fix for #2891~~

~~This fixes the long  timeout since instead of 5 second timeout, we get an 83 minute and 20 second timeout. However, it won't correct the invalid `notmuch` URI issue.~~

### CODE REVIEW

File: notmuch/config.c [hunk 1]
```diff
@@ -30,14 +30,40 @@
...
 #include <config/lib.h>
 #include <stdbool.h>
+#include "notmuch/private.h"
+
+/**
+ * is_valid_notmuch_url - Checks that a URL is in required form.
+ * @retval true url in form notmuch://<absolute path>
+ * @retval false url is not in required form.
+ */
+bool is_valid_notmuch_url(const char *uri)
```
Comment (gahr) [inline notmuch/config.c:40]: static?

File: notmuch/private.h [hunk 2]
```diff
@@ -40,6 +40,7 @@ struct Mailbox;
    (LIBNOTMUCH_MAJOR_VERSION == (major) &&                                        \
     LIBNOTMUCH_MINOR_VERSION == (minor) && LIBNOTMUCH_MICRO_VERSION >= (micro)))
 
+extern const char NmUrlProtocol[];
```
Comment (gahr) [inline notmuch/private.h:43]: Does it need to be extern?

File: notmuch/config.c [hunk 3]
```diff
@@ -30,14 +30,40 @@
...
+{
+  return mutt_istr_startswith(uri, NmUrlProtocol) && uri[NmUrlProtocolLen] == '/';
+}
+
+/**
+ * validate_nm_default_url - Ensure nm_default_url is in form notmuch://<absolute path>
+ */
+int validate_nm_default_url(const struct ConfigSet *cs, const struct ConfigDef *cdef, intptr_t value, struct Buffer *err)
```
Comment (gahr) [inline notmuch/config.c:48]: static?

File: notmuch/config.c (hunk 1 above)
Comment (Austin-Ray) [reply notmuch/config.c]: Fixed

File: notmuch/config.c (hunk 3 above)
Comment (Austin-Ray) [reply notmuch/config.c]: Fixed

File: notmuch/private.h (hunk 2 above)
Comment (Austin-Ray) [reply notmuch/private.h:43]: My understanding is that it does since it's used in `notmuch/notmuch.c` and now `notmuch/config.c`. Am I missing something obvious?

File: notmuch/config.c [hunk 4]
```diff
@@ -30,14 +30,40 @@
...
+
+/**
+ * nm_default_url_validator - Ensure nm_default_url is in form notmuch://<absolute path> - Implements ConfigDef::validator()
+ */
+static int nm_default_url_validator(const struct ConfigSet *cs, const struct ConfigDef *cdef, intptr_t value, struct Buffer *err)
+{
+  const char *uri = (const char *) value;
+  if (!is_valid_notmuch_url(uri))
+  {
+    mutt_buffer_printf(err, _("nm_default_url must be in form: notmuch://<absolute path> . Current value %s"), uri);
```
Comment (flatcap) [inline notmuch/config.c:53]: It'd be nice to show the user the current value, but mind if we shorten it to just the hint?

On an 80 char screen, you're likely to see:
```
|                                                                                |
|nm_default_url must be in form: notmuch://<absolute path> . Current value notmuc|
|                                                                                |
```

File: notmuch/private.h (hunk 2 above)
Comment (gahr) [reply notmuch/private.h:43]: No, I was :)

File: notmuch/config.c (hunk 4 above)
Comment (flatcap) [reply notmuch/config.c:53]: Hmm...  That looks nice, but...

I wasn't thinking about config files, just the on-screen look.
Unfortunately, I've just tested that with newlines and it doesn't work.

There is a hack `mutt_window_reflow_message_rows()`, but intercepting the message would be a pain.

Comment (Austin-Ray) [reply notmuch/config.c:53]: Ah, I see what you mean. When a user runs `:set nm_default_url`, right? I'll trim up the message.

Comment (flatcap) [reply notmuch/config.c:53]: thanks

Comment (Austin-Ray) [reply notmuch/config.c]: Trimmed the message a bit to reduce character count by 13.

`set nm_default_url="notmuch://"` now returns:

 ```
nm_default_url must be: notmuch://<absolute path> . Current: notmuch://
```

from:

```
nm_default_url must be in form: notmuch://<absolute path> . Current value notmuch://
```

**Review by flatcap — APPROVED** [review]
