### PR TITLE
Make sure buffers are initialized on error

### LINKED ISSUE #2145: Messy index lines
## Expected Behaviour
Index displayed correctly.

## Actual Behaviour

Everything other looks okay but index:
```
│�L�D�U
│�L�D�U
│�L�D�U
│ |iE�U
│ |iE�U
│ |iE�U
│ |iE�U
│ |iE�U
│ |iE�U
│�L�D�U
│�L�D�U
│�L�D�U
│�L�D�U
│�L�D�U
│�L�D�U
│�L�D�U
│�L�D�U
```

(Middle lines changed because I moved selection. I can “reset” lines with <kbd>Ctrl</kbd>+<kbd>L</kbd>.)

## Steps to Reproduce

I don’t know anything sure about reproduction (yet).
I’m using `i3` and I sometimes face this after recalling `neomutt` from scratchpad (but maybe it has nothing to do with it).

## How often does this happen?

- Sometimes

## When did it start to happen?

First saw _about_ a month ago.

## NeoMutt Version

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.4.15-arch1-1 (x86_64)
ncurses: ncurses 6.1.20180127 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens 
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify 
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +sasl +smime 
  -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

```
$ echo $TERM
rxvt-unicode-256color
```

Changing `index_format` didn’t help.

### PR DESCRIPTION
**Pull request by zsugabubus**
Because of lack of proper error propagation functions could return
without touching `buf`.

* **What does this PR do?**
Initializes such buffers.

* **What are the relevant issue numbers?**
Fixes #2145. (And absolutely not sure, but maybe #2110 (at least the garbage).)

### CODE REVIEW

File: index.c [hunk 1]
```diff
@@ -927,9 +929,6 @@ int index_color(int line)
  */
 void mutt_draw_statusline(int cols, const char *buf, size_t buflen)
 {
-  if (!buf)
```
Comment (zsugabubus) [inline index.c:930]: This check is redundant. There is one more 10 lines below.

Comment (gahr) [reply index.c:930]: I’d rather fail earlier than later

**Comment by gahr** [comment]
Thanks that looks good, I’ll have a closer look later

File: index.c (hunk 1 above)
Comment (zsugabubus) [reply index.c:930]: Ah, just 10 lines and happens nothing in between.

Then what about moving both checks here?

Comment (gahr) [reply index.c:930]: Definitely!

File: sidebar.c [hunk 2]
```diff
@@ -294,10 +294,13 @@ static const char *sidebar_format_str(char *buf, size_t buflen, size_t col, int
...
 {
-  if (!buf || !box || !sbe)
+  if (!buf)
     return;
 
-  mutt_str_strfcpy(sbe->box, box, sizeof(sbe->box));
+  if (box && sbe)
+    mutt_str_strfcpy(sbe->box, box, sizeof(sbe->box));
+  else
+    buf[0] = '\0';
```
Comment (gahr) [inline sidebar.c:303]: Is it correct to keep going if either `box` or `sbe` are not set?

How about just setting `buf[0] = '\0'` at the beginning of the function no matter what, then keeping the old check and return if either `buf`, `box`, or `sbe` are NULL?

Comment (zsugabubus) [reply sidebar.c:303]: What about padding?

File: index.c (hunk 1 above)
Comment (zsugabubus) [reply index.c:930]: Okay.

(I just wondered–because I see at lots of places–that are these `buf != NULL` checks really necessary? The most places I think `buf` is some array on stack, but if it is `malloc()`ed, the `NULL` check should be done immediately after allocation, so `NULL`s should never be passed to any functions.)

File: sidebar.c (hunk 2 above)
Comment (gahr) [reply sidebar.c:303]: What about it? I don’t think you can do much if any of those params are null.

How about just making sure buf is null-terminated and return as early as possible?

Comment (flatcap) [reply sidebar.c:303]: It turns out that the checks are overkill; none of them can be `NULL`.
There's only one caller and:
- `buf` is `char str[256];`
- `box` is `struct Buffer result = mutt_buffer_make(256);`
- `sbe` is dereferenced before the call: `if (entry->is_hidden)`
