### PR TITLE
Fixes #2154 by replacing mutt_str_replace calls on C_SmimeEncryptWith

### LINKED ISSUE #2154: Opening postponed message encrypted with S/MIME lead to SIGABRT
When postponing an S/MIME encrypted message and opening it again, neomutt crashes with a SIGABRT: `free() invalid pointer`.

## Expected Behaviour
It should not crash, decrypt the message and open the editor for further editing,

## Actual Behaviour
Crash

## Steps to Reproduce
Postpone an encrypted message and reopen it for further editing. It doesn't seem to matter if gpgme is used, or if `postpone_encrypt` is activated or not. 

## How often does this happen?

- Always

## When did it start to happen?
I started using neomutt a week ago. It always crashed like this. 

## NeoMutt Version
At least 1.13.4 but the git version crashes as well. 

```
NeoMutt 20191207
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.5.4-arch1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.1.20180127)
libidn2: 2.3.0 (compiled with 2.3.0)
GPGme: 1.13.1
libnotmuch: 5.2.0
hcache backends: kyotocabinet, gdbm, lmdb

Configure options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --gpgme --sqlite --autocrypt --lua --notmuch --gss --gnutls --sasl --with-ui=ncurses --with-idn2=/usr --disable-idn --idn2 --lmdb --kyotocabinet --gdbm

Compilation CFLAGS: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash

Compile options:
  +autocrypt +bkgdset +color +curs_set +fcntl -flock -fmemopen +futimens
  +getaddrinfo +gnutls +gpgme +gss +hcache -homespool +idn +inotify
  -locales_hack +lua +meta -mixmaster +nls +notmuch -openssl +pgp +sasl +smime
  +sqlite +start_color +sun_attachment +typeahead
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info
I'm running a single instance of Neomutt on Arch Linux and I'm using Maildir. 
I tried to narrow down the problem and here is a backtrace:
```
#0  0x00007ffff779fce5 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff7789857 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff77e32b0 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff77ea74a in  () at /usr/lib/libc.so.6
#4  0x00007ffff77ec13c in _int_free () at /usr/lib/libc.so.6
#5  0x0000555555656bd6 in mutt_mem_free (ptr=ptr@entry=0x5555556b8e18 <C_SmimeEncryptWith>) at mutt/memory.c:75
#6  0x000055555565a2c6 in mutt_str_replace (p=0x5555556b8e18 <C_SmimeEncryptWith>, s=s@entry=0x7fffffff7130 "aes256") at mutt/string.c:457
#7  0x00005555555c542d in mutt_parse_crypt_hdr (p=<optimized out>, set_empty_signas=set_empty_signas@entry=true, crypt_app=crypt_app@entry=4096) at postpone.c:613
#8  0x00005555555c6054 in mutt_get_postponed (ctx=ctx@entry=0x5555559a7b30, hdr=hdr@entry=0x555555a32300, cur=cur@entry=0x7fffffff7a68, fcc=fcc@entry=0x7fffffff7a80) at postpone.c:456
#9  0x00005555555d2887 in ci_send_message (flags=<optimized out>, flags@entry=0, e_templ=<optimized out>, e_templ@entry=0x0, tempfile=tempfile@entry=0x0, ctx=0x5555559a7b30, el=el@entry=0x0) at send.c:1965
#10 0x000055555559a059 in mutt_index_menu (dlg=<optimized out>) at index.c:3499
#11 0x0000555555573e0b in main (argc=<optimized out>, argv=0x7fffffffd1b8, envp=<optimized out>) at main.c:1165
```
It seems to happen when freeing the old memory of `C_SmimeEncryptWith` in the line `mutt_str_replace(&C_SmimeEncryptWith, smime_cryptalg)` in `postpone.c`.

### PR DESCRIPTION
**Pull request by LarsHaalck**
Replaces calls of `mutt_str_replace` on `C_SmimeEncryptWith`  with `cs_subset_str_string_set`
effectively resolving  #2154

### CODE REVIEW

File: ncrypt/smime.c [hunk 1]
```diff
@@ -2480,6 +2481,9 @@ int smime_class_send_menu(struct Email *e)
         e->security |= SEC_ENCRYPT;
         do
         {
+
+          struct Buffer errmsg = { 0 };
```
Comment (flatcap) [inline ncrypt/smime.c]: Please can you change this to `= mutt_buffer_make(0)`
This is our preferred way to create `Buffer`s on the stack.
(It's not widespread in the code, yet, because it's fairly new).

File: ncrypt/smime.c [hunk 2]
```diff
@@ -2524,25 +2533,36 @@ int smime_class_send_menu(struct Email *e)
...
-                  mutt_str_replace(&C_SmimeEncryptWith, "aes256");
+                  rc = cs_subset_str_string_set(NeoMutt->sub,
+                      "smime_encrypt_with", "aes256", &errmsg);
                   break;
               }
               break;
 
             case 4:
-              FREE(&C_SmimeEncryptWith);
+              C_SmimeEncryptWith = NULL;
```
Comment (flatcap) [inline ncrypt/smime.c]: Argh!  That's not what I meant.  Sorry, entirely my fault.  I should have been clearer.
I meant to set the string to `NULL` using the config function:
```c
cs_subset_str_string_set(..., NULL, ...);
```

Using the config function will mean old values are freed and notifications are sent.

File: ncrypt/smime.c [hunk 3]
```diff
@@ -2524,25 +2533,36 @@ int smime_class_send_menu(struct Email *e)
...
               break;
           }
+          if (CSR_RESULT(rc) != CSR_SUCCESS)
+          {
+            if (!mutt_buffer_is_empty(&errmsg))
+            {
+              mutt_error("%s", errmsg.data);
+              FREE(&errmsg.data);
+            }
+          }
```
Comment (flatcap) [inline ncrypt/smime.c]: Please change the `FREE()` to a `mutt_buffer_dealloc()`.
Also, move it after the `if` clause, so it's at the same scope as the `mutt_buffer_make()`.

Currently, the `Buffer` will allocate a string in `Buffer.data`, but if the implementation changes we don't want to have to alter all the callers.

File: ncrypt/smime.c [hunk 4]
```diff
@@ -2524,25 +2533,36 @@ int smime_class_send_menu(struct Email *e)
...
+              C_SmimeEncryptWith = NULL;
             /* (c)lear */
             /* fallthrough */
             case -1: /* Ctrl-G or Enter */
               choice = 0;
               break;
           }
+          if (CSR_RESULT(rc) != CSR_SUCCESS)
+          {
+            if (!mutt_buffer_is_empty(&errmsg))
```
Comment (flatcap) [inline ncrypt/smime.c]: After moving the `FREE()`, see below, we can combined these two `if` clauses.

File: postpone.c [hunk 5]
```diff
@@ -610,7 +610,19 @@ SecurityFlags mutt_parse_crypt_hdr(const char *p, bool set_empty_signas, Securit
...
+        smime_cryptalg, &errmsg);
+    if (CSR_RESULT(rc) != CSR_SUCCESS)
+    {
+      if (!mutt_buffer_is_empty(&errmsg))
+      {
+        mutt_error("%s", errmsg.data);
+        FREE(&errmsg.data);
+      }
+    }
+  }
```
Comment (flatcap) [inline postpone.c]: ... and the same changes as above for this function

File: ncrypt/smime.c (hunk 1 above)
Comment (LarsHaalck) [reply ncrypt/smime.c]: done

File: ncrypt/smime.c (hunk 2 above)
Comment (LarsHaalck) [reply ncrypt/smime.c]: yes sorry about that. I could have just thought about this line a few more seconds.

**Comment by LarsHaalck** [comment]
I included all your comments in the last (amended) commit.

**Comment by flatcap** [comment]
Hmm... you've force-pushed, but the new commit (0065f744ac) is the same as the old (1d436ed819).

**Comment by LarsHaalck** [comment]
Ups. That was not what I wanted. Give me a second.

**Comment by flatcap** [comment]
Thanks.  I've just made a few last-minute tidies:
- Run clang-format on the code
- Add some `()`s around logic
- Use `mutt_bs2()` macro to get `Buffer` contents
- 'Fixes:' comment in the log -- see [Closing issues using keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords)
