### PR TITLE
Cache an Email's tags in the header cache

### LINKED ISSUE #2823: imap_qresync breaks imap keyword support
## Expected Behaviour

* When I type `l~YJunk`, neomutt list messages with the `Junk` IMAP keyword.
* When I select a particular message and press the key I've bound to the `modify-labels` command, neomutt shows existing IMAP keywords. (Per https://neomutt.org/feature/custom-tags)

## Actual Behaviour

* No messages are listed.
* No keywords are listed.

I also think I've observed keywords being changed in strange ways, but I'm not yet confident that's neomutt's fault.

## Steps to Reproduce

(Note: I'm running my own IMAP server. dovecot 2.3.11.3 on OpenBSD 6.8.)

* Put `set imap_qresync=yes` in `~/.neomuttrc`, and configure it to connect to my imap server. (Mostly-complete `.neomuttrc` included below.)

* Delete my neomutt caches: `rm -r ~/.cache/neomutt/*`

* Run `neomutt`.

  * The first time, it works. If I search for the `Junk` tag using `l~YJunk`, there are many results. If I select a message I know has the label and use the `modify-labels` command (bound to `), I see the keyword there.

* Exit neomutt.

* Run `neomutt` again.

  * This time, it's broken. If I search with `l~YJunk`, there are no results. If I select the message and press `, I don't see the keyword.

## How often does this happen?

The above steps reproduce it always.

In general use, I've found the keywords sometimes work and sometimes don't.

## When did it start to happen?

I'm not sure. I can't remember a time when I've been really sure IMAP keyword support was working for me.

## NeoMutt Version

```
NeoMutt 20210205
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: OpenBSD 6.9 (amd64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7.20081102)
libiconv: 1.16
libidn2: 2.3.0 (compiled with 2.3.0)
LibreSSL: LibreSSL 3.3.1
OpenSSL: LibreSSL 3.3.1
storage: kyotocabinet, tdb

Configure options: --mandir=/usr/local/man --with-ui=ncurses --docdir=/usr/local/share/doc/neomutt --with-lock=flock --idn=0 --idn2 --fmemopen --ssl --tdb --debug --kyotocabinet

Compilation CFLAGS: -O2 -pipe -g  -I/usr/local/include -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +bkgdset +color +curs_set -fcntl +flock +fmemopen +futimens 
  +getaddrinfo -gnutls -gpgme -gss +hcache -homespool +idn -inotify 
  -locales_hack -lua +meta -mixmaster +nls -notmuch +openssl +pgp +regex -sasl 
  +smime -sqlite +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Operating System and its version

OpenBSD current

* Were you using multiple copies of NeoMutt at once?

No

* Were you using 'screen' or 'tmux'?

tmux

* Is your email local (maildir) or remote (IMAP)?

IMAP

Here's a copy of ~/.neomuttrc with my aliases removed for privacy:

```
##
## IMAP, and folder configuration
##

set folder=imaps://exoco.falsifian.org/
set imap_user=falsifian
set imap_pass=`cat "$HOME/w/misc-sec/exoco_mail_password"`
set imap_qresync=yes
set spoolfile=+INBOX  # Show IMAP inbox on startup.
set ssl_force_tls=yes

# Where to save draft ("postponed") and sent messages.

set postponed=+Drafts
set record=+Sent


##
## Aliases
##

# (Various lines like "alias X Y@example.com")


##
## Miscellaneous
##

set from="James Cook <falsifian@falsifian.org>"
# See [[id:1f3563db-cb6d-4976-af8d-063c43b2c12e][Try updating neomutt to
# include commit 231ac261.]] In theory the default is already no, but I see
# neomutt advertising new mail automatically, so let's try setting this
# explicitly.
#
# Actually, even this doesn't seem to work. Hrmph.
set imap_idle=no
set index_format="%[%FT%RZ] %Z %-15.15L %s"
set pager_index_lines=5
set pager_stop
set mark_old=no
set send_charset="utf-8"

bind index "\Ca" toggle-read
unbind * d  # Make it (hopefully) really hard to accidentally delete messages.

# Caching. 2020-09-15 I tried some values for header_cache_backend.
# Neomutt complained everything I tried was invalid except "kyotocabinet".
set header_cache_backend="kyotocabinet"
# Use the same directory for both caches. (The manual says this will work.)
set header_cache="~/.cache/neomutt"
set message_cachedir="~/.cache/neomutt"

# Per-recipient settings, and generic default settings. (Without the default
# send-hook, the per-recipient settings would stick, since they last until the
# end of the session.)

send-hook . 'unmy_hdr From: ; set signature="echo James|"'
send-hook '~t ^(agora-.*@agoranomic.org\|agora@listserver.tue.nl)$' 'my_hdr From: Falsifian <agora@falsifian.org> ; set signature="echo Falsifian|"'

# Header weeding and ordering
ignore *
unignore from date subject to cc list-id reply-to
hdr_order subject from date to cc list-id reply-to

# From https://neomutt.org/feature/custom-tags
bind index,pager \` modify-labels

# I tried these but got something about an SSL I/O error. So, instead, I'm relying on my OS's mail sending ability.
#set smtp_user="falsifian"
#set smtp_url="smtps://falsifian@exoco.falsifian.org:587"
```

### PR DESCRIPTION
**Pull request by gahr**
Fixes #2823

### CODE REVIEW

File: email/tags.c [hunk 1]
```diff
@@ -194,7 +195,7 @@ bool driver_tags_replace(struct TagList *head, char *tags)
     struct ListNode *np = NULL;
     STAILQ_FOREACH(np, &hsplit, entries)
     {
-      driver_tags_add(head, np->data);
+      driver_tags_add(head, mutt_str_dup(np->data));
     }
     mutt_list_free(&hsplit);
```
Comment (flatcap) [inline email/tags.c:200]: We could cheat a little here:
- drop the `mutt_str_dup()`
- use `mutt_list_clear()` instead
- (and maybe add a comment to explain what's going on :-)

**Review by flatcap — APPROVED** [review]
