### PR TITLE
imap: ensure we can't delete the current selected mailbox

### LINKED ISSUE #1417: Crash during deletion of the selected mailbox
## Expected Behaviour

Not crashing :p

## Actual Behaviour

NeoMutt crashed

## Steps to Reproduce

Delete a selected mailbox.

## How often does this happen?

- Always

## NeoMutt Version

master (a2d57569c fix some msg_new update)
NeoMutt 20180716-638-a2d575

## Backtrace:

```
#0  0x00007ffff5fc7730 in __write_nocancel () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff7034b25 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#2  0x00007ffff702f66b in BIO_write () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#3  0x00007ffff742fa4b in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#4  0x00007ffff7430260 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#5  0x00007ffff7438751 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#6  0x00007ffff7436b55 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#7  0x00007ffff7440cd9 in SSL_shutdown () from /usr/lib/x86_64-linux-gnu/libssl.so.1.1
#8  0x0000555555665c43 in ssl_socket_close (conn=0x555555b270f0) at conn/ssl.c:1387
#9  0x0000555555663fa1 in ssl_socket_close_and_restore (conn=0x555555b270f0) at conn/ssl.c:631
#10 0x0000555555660ce5 in mutt_socket_close (conn=0x555555b270f0) at conn/socket.c:114
#11 0x000055555564cef5 in cmd_handle_fatal (adata=0x555555b268c0) at imap/command.c:164
#12 0x000055555564f80a in cmd_handle_untagged (adata=0x555555b268c0) at imap/command.c:1050
#13 0x000055555564fb96 in imap_cmd_step (adata=0x555555b268c0) at imap/command.c:1147
#14 0x0000555555650326 in imap_cmd_idle (adata=0x555555b268c0) at imap/command.c:1391
#15 0x00005555556532bb in imap_check (adata=0x555555b268c0, force=false) at imap/imap.c:1334
#16 0x0000555555656926 in imap_mbox_check (ctx=0x555555ae0560, index_hint=0x7fffffffb0b4) at imap/imap.c:2554
#17 0x00005555555d2d32 in mx_mbox_check (ctx=0x555555ae0560, index_hint=0x7fffffffb0b4) at mx.c:1101
#18 0x000055555558edf2 in mutt_index_menu () at curs_main.c:1046
#19 0x00005555555be260 in main (argc=1, argv=0x7fffffffe138, envp=0x7fffffffe148) at main.c:1216
```

### PR DESCRIPTION
**Pull request by sileht**
imap: ensure we can't delete the current selected mailbox

Closes #1417

### CODE REVIEW

**Comment by flatcap** [comment]
The fix looks good for now, but I'd lean the other way and say there's nothing special about the current folder.

We'd need a notification system first, but I'd expect:
- User asks to delete mailbox
- Backend notifies viewers of impending deletion
- Backend deletes mailbox
- MXAPI, on seeing success, selects the next mailbox

File: browser.c [hunk 1]
```diff
@@ -1685,6 +1685,15 @@ void mutt_select_file(char *file, size_t filelen, int flags, char ***files, int
           char msg[SHORT_STRING];
           int nentry = menu->current;
 
+          // TODO(sileht): It could be better to select INBOX instead. But I
+          // don't want to manipulate Context/AllMailboxes/mailbox->account here for now.
+          // Let's just protect neomutt against crash for now. #1417
+          if (mutt_str_strcmp(Context->mailbox->path, state.entry[nentry].name) == 0)
+          {
+            mutt_error(_("Can't delete currenly selected mailbox"));
```
Comment (flatcap) [inline browser.c]:
```suggestion
            mutt_error(_("Can't delete currently selected mailbox"));
```

Comment (sileht) [reply browser.c]: fixed
