### PR TITLE
Check size of long using LONG_MAX instead of __WORDSIZE

### LINKED ISSUE #2344: Unit tests fail on Musl/Busybox
OS: Alpine (Musl LibC/Busybox)

Build fine when check is disabled.

Unit tests failure:
```
Test test_mutt_str_atol...                      [ FAILED ]
  Case 2147483647:
    mutt_str_atol.c:134: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: 0, Got: 0
      result: Expected: 9223372036854775807, Got: 2147483647
  Case -2147483648:
    mutt_str_atol.c:134: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: 0, Got: 0
      result: Expected: -9223372036854775808, Got: -2147483648
  Case 2147483648:
    mutt_str_atol.c:134: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -2, Got: 0
      result: Expected: 9223372036854775807, Got: 2147483648
  Case 2147483649:
    mutt_str_atol.c:134: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -2, Got: 0
      result: Expected: 9223372036854775807, Got: 2147483649
  Case 2147483650:
    mutt_str_atol.c:134: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -2, Got: 0
      result: Expected: 9223372036854775807, Got: 2147483650
  Case -2147483649:
    mutt_str_atol.c:134: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -2, Got: 0
      result: Expected: -9223372036854775808, Got: -2147483649
  Case -2147483650:
    mutt_str_atol.c:134: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -2, Got: 0
      result: Expected: -9223372036854775808, Got: -2147483650
  Case -2147483651:
    mutt_str_atol.c:134: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -2, Got: 0
      result: Expected: -9223372036854775808, Got: -2147483651
Test test_mutt_str_atos...                      [ OK ]
Test test_mutt_str_atoui...                     [ FAILED ]
  Case 4294967296:
    mutt_str_atoui.c:105: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -1, Got: -2
      result: Expected: 0, Got: 0
  Case 4294967297:
    mutt_str_atoui.c:105: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -1, Got: -2
      result: Expected: 0, Got: 0
  Case 4294967298:
    mutt_str_atoui.c:105: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -1, Got: -2
      result: Expected: 0, Got: 0
  Case -3:
    mutt_str_atoui.c:105: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: 0, Got: -2
      result: Expected: 4294967293, Got: 0
  Case  -3:
    mutt_str_atoui.c:105: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: 0, Got: -2
      result: Expected: 4294967293, Got: 0
  Case   -3:
    mutt_str_atoui.c:105: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: 0, Got: -2
      result: Expected: 4294967293, Got: 0
Test test_mutt_str_atoul...                     [ FAILED ]
  Case 4294967296:
    mutt_str_atoul.c:111: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -1, Got: 0
      result: Expected: 18446744073709551615, Got: 4294967296
  Case 4294967297:
    mutt_str_atoul.c:111: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -1, Got: 0
      result: Expected: 18446744073709551615, Got: 4294967297
  Case 4294967298:
    mutt_str_atoul.c:111: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: -1, Got: 0
      result: Expected: 18446744073709551615, Got: 4294967298
  Case -3:
    mutt_str_atoul.c:111: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: 0, Got: 0
      result: Expected: 4294967293, Got: 18446744073709551613
  Case  -3:
    mutt_str_atoul.c:111: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: 0, Got: 0
      result: Expected: 4294967293, Got: 18446744073709551613
  Case   -3:
    mutt_str_atoul.c:111: Check (retval == tests[i].retval) && (result == tests[i].result)... failed
      retval: Expected: 0, Got: 0
      result: Expected: 4294967293, Got: 18446744073709551613
```

### PR DESCRIPTION
**Pull request by gahr**
Fixes #2344

### CODE REVIEW

File: test/test_common.h [hunk 1]
```diff
@@ -39,4 +39,6 @@ void test_init(void);
     }                                                                          \
   } while (false)
 
+#define LONG_IS_64 (LONG_MAX == 9223372036854775807)
```
Comment (flatcap) [inline test/test_common.h:42]: Would this need a `UL` suffix?
