### PR TITLE
Do not link in a new Account after a failed login 

### LINKED ISSUE #1690: Crash when opening an IMAP mailbox after a login failure
As reported on the neomutt-devel mailling list, NeoMutt crashes when trying to open any folder after a failed IMAP login.

The proposed patch is

```diff
diff --git a/imap/imap.c b/imap/imap.c                                                                                                                      
index 60c3b3e94..d1d89fb84 100644                                                                                                                           
--- a/imap/imap.c                                                                                                                                           
+++ b/imap/imap.c                                                                                                                                           
@@ -1820,7 +1820,7 @@ int imap_sync_mailbox(struct Mailbox *m, bool expunge, bool close)                                                                    
  */                                                                                                                                                        
 struct Account *imap_ac_find(struct Account *a, const char *path)                                                                                          
 {                                                                                                                                                          
-  if (!a || (a->magic != MUTT_IMAP) || !path)                                                                                                              
+  if (!a || (a->magic != MUTT_IMAP) || !path || !a->adata)                                                                                                 
     return NULL;                                                                                                                                           
```

This kinds of fix the crash, but it looks wrong to me that we ever get an Account with attached adata.

### PR DESCRIPTION
**Pull request by gahr**
Fixes #1690

### CODE REVIEW

File: init.c [hunk 1]
```diff
@@ -1370,6 +1370,11 @@ static enum CommandResult parse_mailboxes(struct Buffer *buf, struct Buffer *s,
     {
       //error
       mailbox_free(&m);
+      if (new_account)
+      {
+        TAILQ_REMOVE(&AllAccounts, TAILQ_LAST(&AllAccounts, AccountList), entries);
```
Comment (flatcap) [inline init.c]: Am I missing something, or:
```suggestion
        TAILQ_REMOVE(&AllAccounts, a, entries);
```

Comment (gahr) [reply init.c]: heh yes of course
