### PR TITLE
Do not attempt to copy from a FILE* onto itself

### LINKED ISSUE #3040: <sync-mailbox> unable to write to mailbox after manually linking threads with <link-threads>
## Expected Behaviour

Sync mailbox after manually linking threads with `<link-threads>`

## Actual Behaviour

Neomutt successfully links threads internally/in the gui but throws an error when subsequently running `<sync-mailbox>`
The error reads:    `"Unable to write /path/to/folder/mail/dir"`

## Steps to Reproduce

Tag several emails and execute `<link-threads>` then `<sync-mailbox>`.

## How often does this happen?

- Always

*I reproduced this on all accounts and within several folders in each*

## When did it start to happen?

This was the first time I attempted to manually create an email thread with <link-threads>

## NeoMutt Version

```
NeoMutt 20210205-747-27855a
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.13.13-arch1-1 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn2: 2.3.2 (compiled with 2.3.2)
GPGME: 1.16.0
GnuTLS: 3.7.2
libnotmuch: 5.4.0
storage: kyotocabinet, gdbm, bdb, tdb, lmdb
compression: lz4, zlib, zstd

Configure options: --autocrypt --bdb --disable-idn --full-doc --gdbm --gnutls --gpgme --gss --idn2 --kyotocabinet --lmdb --lua --lz4 --notmuch --sasl --tdb --with-lock=fcntl --with-ui=ncurses --zlib --zstd

Compilation CFLAGS: -g -O2 -std=c99 -fno-delete-null-pointer-checks -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -DNCURSES_WIDECHAR -I/include -I/usr/include/

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo +gnutls +gpgme +gss 
  +hcache -homespool +idn +inotify -locales_hack +lua -mixmaster +nls +notmuch 
  -openssl +pgp +regex +sasl +smime +sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"
```

## Extra Info

Arch Linux - version 2021.09.01 / kernel 5.13.13
The email is maildir using mbsync/isync

I ran neomutt with **debug** level 5. Here are the relevant lines from the output:
``` log
[2021-09-24 01:06:54]<M> sync_mailbox() Writing /path/to/mail/dir...
[2021-09-24 01:06:54]<5> msgwin_recalc() recalc done, request WA_REPAINT
[2021-09-24 01:06:54]<5> msgwin_repaint() repaint done
[2021-09-24 01:06:54]<4> progress_update() updating progress: 0
[2021-09-24 01:06:54]<4> progress_update() updating progress: 0
[2021-09-24 01:06:54]<4> progress_update() updating progress: 10
[2021-09-24 01:06:54]<2> maildir_msg_open_new() Trying /path/to/mail/dir/tmp/cur.xxxxxxxxxxxxxxxxxxxxxxxx.xxx:2,
[2021-09-24 01:06:54]<2> maildir_msg_open_new() Success
[2021-09-24 01:06:54]<1> mx_msg_close() unlinking /path/to/mail/dir/tmp/cur.xxxxxxxxxxxxxxxxxxxxxxxx.xxx:2,
[2021-09-24 01:06:54]<5> msgwin_recalc() recalc done, request WA_REPAINT
[2021-09-24 01:06:54]<5> msgwin_repaint() repaint done
[2021-09-24 01:06:54]<2> sync_mailbox() mbox_sync returned: -1
[2021-09-24 01:06:54]<E> sync_mailbox() Unable to write /path/to/mail/dir
```

This is what my **mbsyncrc** looks like for my accounts in case that matters:
```
IMAPAccount abcdef
Host imap.gmail.com
Port 993
User abcdef@gmail.com
Pass xxxxxxxxxx
SSLType IMAPS
CertificateFile /etc/ssl/certs/ca-certificates.crt

IMAPStore abcdef-remote
Account abcdef

MaildirStore abcdef-local
SubFolders Verbatim
Path ~/Mail/abcdef/
Inbox ~/Mail/abcdef/Inbox

Channel abcdef
Far :abcdef-remote:
Near :abcdef-local:
Patterns *
Create Both
Expunge Both
SyncState *
```

And I have been using my email plenty today and everything else has been working perfectly.

### PR DESCRIPTION
**Pull request by gahr**
Fixes #3040

I introduced this bug in #2908.

### CODE REVIEW

File: copy.c [hunk 1]
```diff
@@ -856,6 +856,12 @@ int mutt_copy_message(FILE *fp_out, struct Email *e, struct Message *msg,
   {
     return -1;
   }
+  if (fp_out == msg->fp)
+  {
+    mutt_debug(LL_DEBUG1, "trying to read/write from/to the same FILE*!\n");
```
Comment (gahr) [inline copy.c:861]: I'm willing to put an assert here.

**Comment by flatcap** [comment]
rebased, clang-format, fix typo

**Review by flatcap — APPROVED** [review]
